### ISSUE TITLE
Suggestion: scheduled server restart for SEserver update

### ISSUE THREAD

**Issue by fr33soul** [TorchAPI/Torch#100]
It's possible to add a scheduled restart feature where, at a certain hour (03:00am) the server restart automatically.

Actually, an out of date server is not listed in the client game cause not updated, also is very difficult for admins to know everytime when an update is released.

With this feature we could prevent this issue cause torch will automatically update it on startup.

**Comment by Jimmacle** [comment]
Will be done in Essentials when the autocommand system is redone.
