### ISSUE TITLE
Mod with script in combination with -nogui 

### ISSUE THREAD

**Issue by blaho** [TorchAPI/Torch#102]
**Torch Version:** 1.1.229.265-64-g3d6806b **SE Version:** 1.183.200

Starting up Torch with the **-nogui**, while loading a world which has a mod with a **script** causes an error:

Could not load file or assembly 'SpaceEngineers.ObjectBuilders, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies

### Expected Behavior
Torch able to start up the DS.

### Observed Behavior
The DS causes an exception.

### Steps to Reproduce
Start Torch with -nogui and load up a world with a mod which has a script.

### Other Information
The world works with vanilla DS.
The world works with Torch if I disable mods.
The world works with Torch with mods which doesn't have a script.
The world works with Torch with all mods, if it's started WITH the GUI.

[The Scarce System.zip](https://github.com/TorchAPI/Torch/files/1278160/The.Scarce.System.zip)
[SpaceEngineers-Dedicated.log.txt](https://github.com/TorchAPI/Torch/files/1278182/SpaceEngineers-Dedicated.log.txt)
[Torch-2017-09-05.log.txt](https://github.com/TorchAPI/Torch/files/1278185/Torch-2017-09-05.log.txt)

**Comment by Equinox-** [comment]
@blaho Grab the patch from [Jenkins](http://torchapi.net:8080/job/Torch/job/Torch/job/staging/lastSuccessfulBuild/artifact/bin/) and let me know if it fixed your issue.

**Comment by blaho** [comment]
I can confirm that the bug was fixed.

Tested on **Torch version** 1.1.229.265-70-gcfda1f8 **SE version** 1.183.300

Thank you.
