### ISSUE TITLE
Blocks in grid list are duplicated

### ISSUE THREAD

**Issue by Phoenix84** [TorchAPI/Torch#105]
**Torch Version:** 1.1.229.265 **SE Version:** 1.183.200

### Expected Behavior
Blocks should only appear once in entity manager.

### Observed Behavior
The same blocks appear multiple times in the entity manager.

### Steps to Reproduce
I just noticed it after I restarted the server after enabling concealment. I didn't notice if it was a problem before that, as I didn't use it before.

### Other Information
World: https://www.dropbox.com/s/nkl37sxhtv0pixh/rexfun.rar?dl=1

First Image: https://media.discordapp.net/attachments/301835879947698177/355183146041475072/image.png
Second Image:
https://media.discordapp.net/attachments/301835879947698177/355183440628416512/image.png

Notice the _[LCD] Panel_ - _[LCD] Panel 5_ entries are duplicated. The grid in question only has 6 LCD panels.

**Comment by Equinox-** [comment]
Cannot reproduce any more.  Observable collections have gone through quite a few changes, so it's likely this has been fixed.
