### ISSUE TITLE
Torch Hosting £5 p/m(NOt a ISSUE)

### ISSUE THREAD

**Issue by MrBenFTW** [TorchAPI/Torch#116]
--Not an issue--

Hello all, I am offering torch hosting for anyone interested. It is by no means a official business. 
--Note--
-No control panel
-You must be able to use remote desktop

Specs: 1xAccount on server with 32GB DDR4 Ram
and 4 cores.

You are responsible for updating and maintaining your server. You will get unlimited slots. and up to 120gb storage (Split with other people)

price starts at £5 p/m (No restrictions).
Contact me for details. 
Or reply to this thread.

**Comment by MrBenFTW** [comment]
How do i add a assignment to this?

**Comment by Taki7o7** [comment]
Annoying

**Comment by MrBenFTW** [comment]
Sorry should i not of post it? 
How do i delete it?

**Comment by Jimmacle** [comment]
Don't advertise here please.
