### ISSUE TITLE
Everyone is admin?

### ISSUE THREAD

**Issue by MrBenFTW** [TorchAPI/Torch#117]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.2.0.0 **SE Version:** 1.184.5

### Expected Behavior
Open players to make friend admin

### Observed Behavior
Open players to make friend admin,, can see that the whole server is admin 
### Steps to Reproduce
1. Launch the game and connect to server.
2.Open 'Players'
3.all players connected are administrator/space master

**Comment by szczepix** [comment]
I don't Observed this Behavior on our 4 servers.

**Comment by Equinox-** [comment]
Is your game world `Sandbox.sbc` configured with Offline?  It needs to be Public.

**Comment by MrBenFTW** [comment]
Ahh that's it. Thanks.
