### ISSUE TITLE
Advanced Backups and Server Config/Cache Backup

### ISSUE THREAD

**Issue by Varaxian** [TorchAPI/Torch#122]
I accidentally found out when purging some files (and admittedly, not checking first), that backups are NOT storing the DS storage folder. This is pretty important to have as a standard, but still low priority as an addition.

o7

**Comment by Equinox-** [comment]
Just to clarify you mean the global mod storage folder, *not* the world mod storage folder.
Mods shouldn't be using that folder for storing anything except cache data since it isn't unique per-world.

**Comment by Varaxian** [comment]
\TORCH\Instance\Storage

**Comment by XeroCreator** [comment]
If I may... while you're working on this, It would be helpful if you can just set the folder you want to save backups in, as well as the backup interval. 
Currently using vanilla at 10m intervals creates a ton of backups but it's still limited to however many you make based on the save intervals... even though i have 72 set... that's still only 12 hours of the day. it would be more efficient to have one every 30 minutes, and have less space being used.

**Comment by Equinox-** [comment]
How would you feel about multiple backup intervals.
For instance, keep 10 daily backups, 10 hourly backups, and 10 10-minute backups.

**Comment by XeroCreator** [comment]
In the past i had backups every 30 minutes, and that gave me a total of 48 backups per-day. Now, adding a daily backup at the end of that day, would also be nice, given you can set that to 30, and only have 30 in a 'daily' backup folder specified in config somewhere. I don't the 10-minute backups are necessary, but for the most part the hourly backups are fine as well. 

Players don't generally mind a 10-20 min rollback over losing EVERYTHING so i don't think it'll be an issue. 

so yeah, that works :p

**Comment by Varaxian** [comment]
In an ideal situation, that would be perfect. However, since server admins are working this as they can due to RL responsibilities, it would be ideal for a custom period to be set. If not possible, then at least 24 (one per hour) for the daily, kept for 7 days and then purged.

Also, while I'm thinking about it, is it possible to move the backups folder out of Instance/Saves/(Worldname)?

Reason: Actual dev time could be better utilized not iterating on this at all, if we could simply right click, zip the entirety of Instance/Saves/(Worldname) on our own accord, instead of having it be a mechanical feature (at least in early development of TORCH, as it is likely a low-priority item).

thanks!

**Comment by Equinox-** [comment]
Advanced backups have since been implemented in a third party plugin https://github.com/sirhamsteralot/TorchBackupSystem

The global storage (not the save storage) folder _should not be used_ for storing anything except disposable cache data since it's not included with workshop items or world copies. If it is being used that way it's a mod problem.

For now this is being closed; we may revisit it in the future.
