### ISSUE TITLE
!restart command does not save game

### ISSUE THREAD

**Issue by zenduin** [TorchAPI/Torch#124]
- [x ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.2.0.0 **SE Version:** 1.184.101

### Expected Behavior
Server warns of restart
Server saves the current game
Server restarts

### Observed Behavior
Server warns of restart
Server starts to save the current game
Server restarts before finishing saving the game
Server rolls back to previous save after reloading game

**Comment by Equinox-** [comment]
This should be fixed since https://github.com/TorchAPI/Torch/commit/d07caea0f6bea49fe91c2e6aa16cbe693ecd4d4c
