### ISSUE TITLE
Server froze on a autosave

### ISSUE THREAD

**Issue by patrickrohmer** [TorchAPI/Torch#125]
- Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- It has happend a couple of times now, always on autosave.

**Torch Version:** v1.2.0 **SE Version:** 1.184.101

### Expected Behavior
What did you expect to happen?
Save and thats all :)

### Observed Behavior
What actually happened?
It froze Torch and I had to shut it down with task manager.

### Steps to Reproduce
1. How did this issue get triggered?
Autosave
2. Write the steps here.

### Other Information
Provide links to game logs or saves here if necessary.
[Torch-2017-09-25.log](https://github.com/TorchAPI/Torch/files/1330338/Torch-2017-09-25.log)
- Check after 19:08:55

**Comment by Equinox-** [comment]
Will be addressed in #129.
