### ISSUE TITLE
[Suggestion] Detection of abusers and SS Goals.

### ISSUE THREAD

**Issue by Alliguierg** [TorchAPI/Torch#126]
Hello. I would like to suggest some functionality to make life easier for admins.

1 - Detection of abuse: The server monitors players that are consuming most of the SS during the time they are online. Warning them and by executing the kick if the player does not solve its abuse.
This function would also have an educational purpose.

2 - SS Goals: The adm defines a minimum SS average. When it is in this minimum state the server should not allow more connections.
This allows the possibility of leaving the limit of players free and determined by the processing capacity of the server.

**Comment by Jimmacle** [comment]
The problem with this is that players themselves don't have a large effect on sim speed, it's what they build that eventually causes performance issues. One could link performance issues to players through block ownership but it's not 100% accurate so it's trickier to solve than it appears.

**Comment by XeroCreator** [comment]
You can have up to around ~60 people alone on a server with star system setup.
adding one grid with full survival use, gives you about a .80-.90 sim speed almost instantly.

During a test on a very powerful server and during Xocliw's stream we had around 32+ people in what was called the 'clangthedral' and we were able to maintain 1.0 sim through this process... until someone turned off the thrusters and attempted to crash us in creative.

**Comment by Equinox-** [comment]
I'm going to implement a PB resource sharing system soon :tm:
Basically you can tell it "I want PBs taking up to 5ms each tick" and that 5ms will be split among all players fairly.
