### ISSUE TITLE
Launch TorchBase in separate app domain

### ISSUE THREAD

**Issue by Equinox-** [TorchAPI/Torch#128]
Issues with types being loaded twice, etc cause problems.
- [ ] Launch TorchBase using a separate AppDomain than the Program launchers use
- [ ] Look into ensuring that [these](https://github.com/KeenSoftwareHouse/SpaceEngineers/blob/master/Sources/VRage/Plugins/MyPlugins.cs#L174) things don't load a different assembly then [this](https://github.com/TorchAPI/Torch/blob/master/Torch/Utils/TorchAssemblyResolver.cs) thing.
- [x] Use [PrivateBinPath](https://docs.microsoft.com/en-us/dotnet/api/system.appdomainsetup.privatebinpath?view=netframework-4.7)
- [ ] Investigate why tests seem to break

**Comment by MrBenFTW** [comment]
Is there a temp fix?

**Comment by Equinox-** [comment]
No, but this is my highest priority ATM.  Should be patched in the next 24h

**Comment by MrBenFTW** [comment]
Thanks!

**Comment by Equinox-** [comment]
@MrBenFTW when you get a chance try this version of torch:
https://build.torchapi.net/job/Torch/job/Torch/job/app_domains/lastSuccessfulBuild/artifact/

**Comment by MrBenFTW** [comment]
Okay

**Comment by Equinox-** [comment]
Fixed in https://build.torchapi.net/job/Torch/job/Torch/job/app_domains/
Will be merged into master as part of Torch v1.3.0
