### ISSUE TITLE
Server not Starting up

### ISSUE THREAD

**Issue by captain1242** [TorchAPI/Torch#134]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.2.0 **SE Version:** 1.184.2

### Expected Behavior
The server to start up

### Observed Behavior
It hangs on:
2017-10-03 20:03:33.293: Loading session: C:\ProgramData\SpaceEngineersDedicated\SESM_3_server1\Saves\apho_map1

### Steps to Reproduce
I don't know, if I would know what caused the problem I wouldn't write here

### Other Information
none

**Comment by Jimmacle** [comment]
Are you sure it's not just taking a long time to load the world?

**Comment by captain1242** [comment]
2 hours? I am pretty sure

**Comment by MrBenFTW** [comment]
check the window, does it say 'selected' if so click anywhere in the console and press a key.

**Comment by captain1242** [comment]
After 5 hours it started ... wth ...

Whatever.
