### ISSUE TITLE
[Suggestion] Add new argument to command: !restart stop

### ISSUE THREAD

**Issue by szczepix** [TorchAPI/Torch#140]
Add new argument to `restart` command for break restart timer and prevent server restart.
Maybe:
`!restart stop` or
`!restart break` or
`!restart cancel`

What do you think about that?

**Comment by Jimmacle** [comment]
Implemented in https://github.com/TorchAPI/Torch/commit/d87cc7f1e70dc145897d925324c270673ca1e61f
