### ISSUE TITLE
[Suggestion] !grids list [username] for admins

### ISSUE THREAD

**Issue by Jentara** [TorchAPI/Torch#141]
Allow players to do their own grids list.   Would help admins with constant searching for lost ships due to game bugs.   (Cause we don't find ships based on pilot error lol)

**Comment by szczepix** [comment]
@Jentara Could you explain your idea? You mean add new arg like `!grids list username` ?

**Comment by XeroCreator** [comment]
Jentara !grids list can be used by players already. 

Though with what szczepix said, a !grids list username would be nice for admins. there's too many 'large grid/static grid items to find players grids in torch. (or you know, put the name there)

**Comment by Jentara** [comment]
We had a user on the server try it and it didn't work.  The other admin watched him in chat (gui) and the command didn't return anything.  It works for admins.   Sounds like maybe more of a bug then?

**Comment by XeroCreator** [comment]
This can ... mostly? be closed, though my above suggestion would be nice.

**Comment by N1Ran** [comment]
This should be closed since !cleanup has this function
"!cleanup list ownedby [username]"
