### ISSUE TITLE
[Suggestion] Reserve space for admins

### ISSUE THREAD

**Issue by Jentara** [TorchAPI/Torch#142]
Be nice if there was a way to reserve slots for admins on their own servers.  So if you set the capacity to 12/12, and have two admins, those admins could always join.

**Comment by Jentara** [comment]
Add on to this...as last night we bumped up to 16/16 and the server still got filled.  Our "regular" players couldn't join.  Maybe instead of just an Admin feature, you could have a VIP feature.  So your regulars could always join.  This would have to be a toggle so that you could open up more space when you know VIP's are not going to be joining.

**Comment by Equinox-** [comment]
How about admins can always join the server regardless of how many players there are?  This would be fairly trivial to implement.

**Comment by szczepix** [comment]
:+1: :+1:

**Comment by szczepix** [comment]
:+1: :+1: 
btw.
What do you think about separate slots:
* default player slots setup 16 slots -ex. 8/16 default players
* VIP player slots setup 10 slots - ex. 5/10 vip players
Server have 26 all slots. - ex. 13/26 all players

**Comment by Equinox-** [comment]
Something like that would probably end up in a plugin, not Torch core.

**Comment by szczepix** [comment]
like Essentials ... ?

**Comment by Equinox-** [comment]
Not sure.  That would come down to design choices.  I'd probably do a
separate separate plugin, which will be more common once we have a plugin
distribution system setup.

**Comment by szczepix** [comment]
but it's possible to do yes?

**Comment by Equinox-** [comment]
Yeah it's possible.

**Comment by Neimoh** [comment]
This was already done in SESE Essentials a few weeks before it died. Rexxar worked some overlooked magic and was able to allow any admin to enter the server even above max player limit.

**Comment by Equinox-** [comment]
Implemented since https://github.com/TorchAPI/Torch/commit/834395bdc3401def1119ec4f6e442a71bf07e7b7
