### ISSUE TITLE
[Suggestion] vote to restart /save for players.

### ISSUE THREAD

**Issue by XeroCreator** [TorchAPI/Torch#144]
- [yup] Is this a suggestion?
Basically, this could even be a plugin for torch, and separate from everything else but probably just as easy to add a command.

So, players notice sim speed dropping, all agree server restart is needed. so they can type !vote restart (number)

specify parameters like 1s, 5m, 10m, 30m on the end. so either restart now, 5 mins etc etc etc. 

just a small addition so players can restart if no admin is around. 
the trick i assume is going by how many players vote and don't vote. I'd just say at least 50% of players must vote yes, if no vote is cast by a logged in player, it is counted as a yes (because they're obviously afk and not paying attention)
if the 5m, 10m, 30m, options are used. then display message saying 'restart in 5-10-30 minutes, please type !vote cancel restart to cancel, i.e. 50% needed to cancel as well. 

dunno if it's even possible but i don't see it being too hard.

**Comment by Kothe** [comment]
I believe this can be closed now?
