### ISSUE TITLE
[Suggestion] Add stop all grids before Torch close save

### ISSUE THREAD

**Issue by szczepix** [TorchAPI/Torch#147]
Add in Torch.Server stop all grids in moving before Torch close save.

**Comment by XeroCreator** [comment]
I think we're missing the 'stop all' in general command. !grids stop large/small/all maybe?

**Comment by Neimoh** [comment]
SESE had an option to stop all ships during startup. We also had the option to stop all during a scheduled shutdown.

**Comment by Equinox-** [comment]
Consolidated into https://github.com/TorchAPI/Torch/issues/164 and a general startup/shutdown trigger in the new commands system.
