### ISSUE TITLE
Change Spawn points

### ISSUE THREAD

**Issue by MrBenFTW** [TorchAPI/Torch#149]
- [x] Is this a suggestion?
Hello, I have a server with a few planets and i would like to add landers for them, Howerver i see no way to do this? is there a mod/ plugin that allows me to change the locations for landers to spawn? Thanks. (if not then this is a suggestion to add to torch :)

**Comment by logan2611** [comment]
I believe you can do this on a stock Space Engineers server, so you should be able to on Torch as well by editing configs.
Try https://steamcommunity.com/app/244850/discussions/0/392184522708216233/

**Comment by MrBenFTW** [comment]
Thanks for the reply, i dont understand where i put this/ how i edit it :)
