### ISSUE TITLE
Staging #22 - Torch can't save to an empty path.

### ISSUE THREAD

**Issue by ProsperCraft** [TorchAPI/Torch#150]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.2.0.663 **SE Version:** 1.84.401

### Expected Behavior
What did you expect to happen?
That it would try to save the config to the proper folder, not a folder that doesn't exist.

### Observed Behavior
What actually happened?

17:53:50.1941 [INFO] Torch: Executing directory: C:\Games\SpaceEngineersServer\
17:53:50.1941 [INFO] PluginManager: Checking for plugin updates...
17:53:50.2091 [INFO] PluginManager: Updated 0 plugins.
17:53:50.2091 [INFO] PluginManager: Loading plugins...
17:53:50.2091 [INFO] PluginManager: Loaded 0 plugins.
17:53:51.6194 [WARN] InstanceManager: No worlds found in the current instance C:\Games\SpaceEngineersServer\Instance.
17:54:06.4034 [WARN] InstanceManager: No worlds found in the current instance C:\Games\SpaceEngineersServer\Instance.
18:08:00.0622 [INFO] InstanceManager: Saved dedicated config.
18:08:00.0671 [ERROR] InstanceManager: Failed to write sandbox config, changes will not appear on server
18:08:00.0671 [ERROR] InstanceManager: System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Torch.Server.Managers.InstanceManager.SaveConfig() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Managers\InstanceManager.cs:line 139

### Steps to Reproduce
1. How did this issue get triggered? 
Started, Torch and edited the config, clicked save, and it failed.

**Comment by Jimmacle** [comment]
It tries to save to the folder specified in the dedicated server configuration, which, given the exception, you didn't fill out. The path in the exception is simply debugging information.

**Comment by ProsperCraft** [comment]
Seeing as Torch downloaded the server for me, should it not know where it is?

**Comment by Jimmacle** [comment]
Torch knows exactly where the server is, it doesn't know where your worlds are. You need to copy the saves you want to use in to Instance\Saves.

**Comment by ProsperCraft** [comment]
I am new to this, but I would expect the flow to be, as listed in the install directions- 

"Unzip the Torch release into its own directory and run the executable. It will automatically download the SE DS and generate the other necessary files."

I don't have saves, so I expected them to be generated when I edited the config and clicked start. no?

**Comment by Jimmacle** [comment]
No, Torch doesn't currently have the code to generate new worlds. You need to make one in SE (or use the vanilla dedicated server) and then copy that in.

**Comment by ProsperCraft** [comment]
I will do that thank you.
