### ISSUE TITLE
Asteroids generation on Torch Server

### ISSUE THREAD

**Issue by SantaSeal** [TorchAPI/Torch#151]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.2.0.0 **SE Version:** 1.184.500

### Expected Behavior
I thought that there would a possibility to turn the asteroids spawning on. Becuase I could't found a setting for that I wanted to change it in the files directly. 
### Observed Behavior
The Torch Server changed my setting back to 4, at the Generate Asteroids setting. But it is a value between 0 and 1, so this is just 0 for the server

### Steps to Reproduce
Try to change it by yourself.

### Other Information
Provide links to game logs or saves here if necessary.

**Comment by Equinox-** [comment]
UI controls have been implemented.  Cannot reproduce Torch resetting this value.
