### ISSUE TITLE
#30 version, wont start from gui

### ISSUE THREAD

**Issue by zarozak** [TorchAPI/Torch#154]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.x.xxx.xxx **SE Version:** 1.xxx.xxx

### Expected Behavior
What did you expect to happen?

### Observed Behavior
torch crashes after starting new instance for world, watchdog fails to start.
run without gui ok

### Steps to Reproduce
torch crashes after starting new instance for world, watchdog fails to start.

### Other Information
Provide links to game logs or saves here if necessary.
took all actions from closed thread but no change.
also no plugins also show in gui/torch

**Comment by XeroCreator** [comment]
The gui and loading in works on #39  staging
