### ISSUE TITLE
Torch Initializer error

### ISSUE THREAD

**Issue by G4rga** [TorchAPI/Torch#155]
- [x ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.2 **

Hy somebody knows whats happening my Torch? This is my log file

16:05:30.6009 [INFO] Initializer: Loading config c:\TORCH\Torch.cfg
16:05:30.8919 [FATAL] Initializer: System.MissingFieldException: A mező nem található: „Sandbox.Engine.Utils.MyFakes.ENABLE_INFINARIO”.
   a következő helyen: Torch.Server.TorchServer..ctor(TorchConfig config)
   a következő helyen: Torch.Server.Initializer.Run() hely: C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Initializer.cs, sor: 85
   a következő helyen: Torch.Server.Program.Main(String[] args) hely: C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Program.cs, sor: 62

What the problem?

**Comment by maxwellrm** [comment]
i had same problem :( after SE update torch crash everytime after start

**Comment by susu** [comment]
You should use the staging version. Master version has that issue, not supported anymore.

Your error messages are hungarian, so:
Amúgy mire használod a Torch-ot? Van valami jóféle magyar szerver? :)

**Comment by G4rga** [comment]
Igen lenne egy csak most nem nagyon megy mert nem jó a Torch...
küzdünk a server sim speeddel de amyg volt Torch addig stabil volt valamennyire...
ha esetleg érdekel DeadMan a server neve kukkansd meg bár most elég ratyi sajnos

**Comment by G4rga** [comment]
I use now the staging Torch but not loaded Plugins. Maybe alternative plugin dll needed?

**Comment by Equinox-** [comment]
This was fixed in 998ff6a13a55a4c6c574ec80a1eb1583b2ed5ae1.
If you use staging Torch you need staging (or other staging based branch) plugins.  Ask on Discord if you have more questions.
