### ISSUE TITLE
[ Sugestion ] Protected grids

### ISSUE THREAD

**Issue by Neimoh** [TorchAPI/Torch#156]
A Late SESE Essentials feature was the ability to protect any Entity ID with toggled features. 
You could enable / disable receiving damage, painted, adding blocks, removing blocks, renaming, converting to ship or converting to station. 
We had the ability to push the offense to a log, auto-kick the player or auto-ban the player based on each type of offense. We could allow overrides for same faction, admin or owner per grid. 

This could tie into the previously posted definable Protection zone which was an older SESE Essentials feature that allowed us to setup anti-griefing bubble zones where all players and entities were invulnerable.

**Comment by Equinox-** [comment]
Joined with #131
