### ISSUE TITLE
[ Suggestion ] Ability to define custom backup location and auto-purge

### ISSUE THREAD

**Issue by Neimoh** [TorchAPI/Torch#157]
We used to be able to define our own backup location for the backup files, Essentials would just move the files from the default folder to your defined location and monitor what was in there per a set amount of days to retain backups and it would just purge the oldest out. 

Some of us run these on limited space for our c:\ and trying to retain a large amount of files to provide better grid recovery options gets space heavy. The ability to push those to a larger secondary backup drive is most helpful especially if our primary drive dies we still have a working world save.

**Comment by Equinox-** [comment]
Use a junction or symbolic directory link for the backups folder.
More advanced options will come in #122
