### ISSUE TITLE
Gracefully Fail for Non-Public Mods

### ISSUE THREAD

**Issue by Neimoh** [TorchAPI/Torch#159]
Torch crash on startup due to an existing mod that has been set to friends only or non-public. Vanilla DS shows entry of Mods Failed to Download and then just hangs, service continues to try to start but won't do anything. You have to manually end the service task to kill everything and attempt a fresh restart. 

You can add any mod to the server and set it to friends only to reproduce. I had the issue on staging build 29, 39 and 40

**Comment by Equinox-** [comment]
Preferred solution to this would be to gracefully fail with a nice error message.
