### ISSUE TITLE
no plugins loaded

### ISSUE THREAD

**Issue by zarozak** [TorchAPI/Torch#162]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.x.xxx.xxx **SE Version:** 1.xxx.xxx

### Expected Behavior
flugin to be loaded

### Observed Behavior
0 plugins loaded

### Steps to Reproduce
happened since torch update

### Other Information
no information found to confirm plugin status or installation
pluggin concealment put in plug in directory, no other action taken
plugin updated/reinstalled in directory

**Comment by k3nnny** [comment]
Hiya!

Same problem here. Also noted on the Concealment's page.

**Comment by Heisenborg** [comment]
Make sure that you created a folders with the name of plugins in the Plugins directory. Like 'Essentials' or 'Concealment' folders and place .zip files of your plugins in appropriate folders. Also, it would be good to let us know what wersion of the Torch you are using.

**Comment by Equinox-** [comment]
Request for help, not an actual issue.  Use the discord for support.
