### ISSUE TITLE
Unable to Start the Torch Server

### ISSUE THREAD

**Issue by SantaSeal** [TorchAPI/Torch#163]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.x.xxx.xxx **SE Version:** 1.xxx.xxx

### Expected Behavior
Just the Normal Server, starting up.

### Observed Behavior
I tried to start the server and then I get a crash message.

11:03:13.8170 [FATAL] Initializer: System.MissingFieldException: Feld nicht gefunden: "Sandbox.Engine.Utils.MyFakes.ENABLE_INFINARIO".
   bei Torch.Server.TorchServer..ctor(TorchConfig config)
   bei Torch.Server.Initializer.Run() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Initializer.cs:Zeile 85.
   bei Torch.Server.Program.Main(String[] args) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Program.cs:Zeile 62.

I already tried to download the Server again. But still the same error. I tried the server on multiple Pc's still the error message. It was always the same one. I used the Server now quite often and it alway started good until yesterday.
Today I made a new server(again). Still the same error Message.
The Log File from Today: 
[Torch-2017-11-02.log](https://github.com/TorchAPI/Torch/files/1437280/Torch-2017-11-02.log)

### Steps to Reproduce
1. Just by Starting the Server
### Other Information
Log File From the Server yesterday:
[Torch-2017-11-01.log](https://github.com/TorchAPI/Torch/files/1437283/Torch-2017-11-01.log)

**Comment by szczepix** [comment]
use build #40 staging version

**Comment by szczepix** [comment]
here https://build.torchapi.net/job/Torch/job/Torch/job/staging/

**Comment by SantaSeal** [comment]
Thank you for giving me this advice. Now the Server works perfectly fine again. I downloaded from this side. N

https://github.com/TorchAPI/Torch/releases 

Didn't know that there would be another one.

**Comment by szczepix** [comment]
For more info join to discord server: https://discord.gg/MeNqKXR
