### ISSUE TITLE
Torch client failed to create junction link.

### ISSUE THREAD

**Issue by Anach** [TorchAPI/Torch#168]
When attempting to launch the Torch client 1.2.0, I'm receiving the following error. It's obviously looking for a path on another machine.
![capture](https://user-images.githubusercontent.com/405509/32479491-2e033f40-c3de-11e7-8277-b6ef78a28a6d.PNG)

**Comment by Jimmacle** [comment]
"Obviously"

That path is left-over debugging information from the build server, it isn't related to any IO being performed by the application.

**Comment by Equinox-** [comment]
Post the log file in Logs/ or the screenshot of the entire window.

**Comment by Anach** [comment]
https://gist.github.com/Anach/1e16d6665463c9fb6bbcb71254df3778

**Comment by Equinox-** [comment]
Yeah it looks like your steam setup is too complicated for it to figure
out.  I'll look into it when I get a chance.

**Comment by Anach** [comment]
Complicated, meaning it's not in Program Files. :)

**Comment by Equinox-** [comment]
This should be fixed so it properly prompts you for the SE install dir.
https://github.com/TorchAPI/Torch/commit/eb97d0d479933f54130fe1f1799186b0f57cde2d
