### ISSUE TITLE
Crash while playing

### ISSUE THREAD

**Issue by Basti91le** [TorchAPI/Torch#172]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.2.0.12232 **SE Version:** 1.184.801

### Expected Behavior
Server is running.

### Observed Behavior
Crashed with error down below.

### Steps to Reproduce
1. Random while playing

### Other Information

[Torch Crash.txt](https://github.com/TorchAPI/Torch/files/1478257/Torch.Crash.txt)

**Comment by Equinox-** [comment]
Should be fixed as of https://github.com/TorchAPI/Torch/commit/22bd56652d35d9dae839b92e3e82b0ccdd785539
