### ISSUE TITLE
Entity Query

### ISSUE THREAD

**Issue by Equinox-** [TorchAPI/Torch#175]
- [x] Entity query standard format 
- [x] Solve issues with block duplication in grids
- [x] Group blocks by type?

**Comment by Equinox-** [comment]
Ideas for entity query format:
- Search by entity type (block type, etc)
- Search by definition ID (type ID, subtype ID)
- Search by owner/builder identity ID, steam ID, and steam name

Colon separated, space separated.
`type:Reactor subtype:LargeReactorSmallGrid owner:Equinox builder:Equinox`

**Comment by XeroCreator** [comment]
It would really help a lot if the tree had a delete button for individual blocks. same w/ a query although i believe this may already be planned. 
i.e. !cleanup delete blocks subtype 'subtypeid' or something similar. 

Export grids option?make it easier to connect to export a blueprint...
import blueprint would be neat too, though i'm not sure how that'd work. .. maybe click import, it imports grid and prompts with a location. but that's probably a terrible idea.

**Comment by Equinox-** [comment]
- [ ] Context Menu for Entities with delete
- [ ] `!cleanup scan/delete` for generic entity queries
