### ISSUE TITLE
First Start Fail

### ISSUE THREAD

**Issue by interfectoren** [TorchAPI/Torch#176]
**Torch Version:** 1.2.0 **SE Version:** 1.xxx.xxx **_Never completed first time setup_**

### Expected Behavior
I was hoping it would install without issue. I don't really understand why this is happening and I didn't really see anyone else with the same issue. I tried reinstalling but got the same problem. 

### Observed Behavior
It didn't initialize. 
![torch issue 2](https://user-images.githubusercontent.com/33457855/33245411-6fdc2f8e-d2d5-11e7-9a6f-67e57cad3690.png)

### Steps to Reproduce
1. Unzipped the torch folder to its install location
2. Ran it. That was literally all I did

### Other Information
![torch issue](https://user-images.githubusercontent.com/33457855/33245357-de516fe8-d2d4-11e7-9778-f6cccca4706d.png)

**Comment by Jimmacle** [comment]
Download the latest version from https://torchapi.net/download/. We're working on making the release process simpler so it's easier to find the right version to use.
