### ISSUE TITLE
Clean install fatal errors

### ISSUE THREAD

**Issue by cubesteak** [TorchAPI/Torch#178]
- [ Yes, just Torch] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ Yes, done it multiple times.] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ No] Is this a suggestion?

**Torch Version:** 1.2.0 **SE Version:** 1.185.2

### Expected Behavior
I expected the install to download a new SE DS and then run Torch.  I've searched the issues, but can't see a similar one.

### Observed Behavior
The install downloads SE DS but then dies with a fatal error: [FATAL] Initializer: System.MissingFieldException: Field not found: 'Sandbox.Engine.Utils.MyFakes.ENABLE_INFINARIO'.

### Steps to Reproduce
1. Simply download Torch Server and run on a clean install.

### Other Information

Log from the error:
00:25:08.3542 [INFO] SteamCMD: Downloading SteamCMD.
00:25:09.0534 [INFO] SteamCMD: SteamCMD downloaded successfully!
00:25:09.0534 [INFO] SteamCMD: Checking for DS updates.
00:25:12.5251 [INFO] SteamCMD: Steam Console Client (c) Valve Corporation
00:25:12.6267 [INFO] SteamCMD: -- type 'quit' to exit --
00:25:12.7283 [INFO] SteamCMD: Loading Steam API...OK.
00:25:12.8298 [INFO] SteamCMD: 
00:25:14.1033 [INFO] SteamCMD: Connecting anonymously to Steam Public...Logged in OK
00:25:17.3337 [INFO] SteamCMD: Waiting for user info...OK
00:25:17.6394 [INFO] SteamCMD:  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
00:25:19.0417 [INFO] SteamCMD:  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
00:25:21.0076 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 1.17 (22129568 / 1890333858)
00:25:23.0154 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 4.06 (76715217 / 1890333858)
00:25:25.0173 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 7.88 (148897725 / 1890333858)
00:25:27.0046 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 22.69 (428829059 / 1890333858)
00:25:29.0251 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 34.11 (644736347 / 1890333858)
00:25:31.0134 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 46.16 (872500041 / 1890333858)
00:25:33.0203 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 51.50 (973517021 / 1890333858)
00:25:35.0193 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 60.32 (1140205333 / 1890333858)
00:25:37.0105 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 65.40 (1236371098 / 1890333858)
00:25:39.0007 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 73.62 (1391655243 / 1890333858)
00:25:41.0095 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 76.01 (1436884832 / 1890333858)
00:25:43.0173 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 78.55 (1484938985 / 1890333858)
00:25:45.0017 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 82.26 (1555016284 / 1890333858)
00:25:47.0105 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 89.11 (1684492129 / 1890333858)
00:25:49.0203 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 91.74 (1734159823 / 1890333858)
00:25:51.0046 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 92.81 (1754502168 / 1890333858)
00:25:53.0154 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.22 (1875653794 / 1890333858)
00:25:55.0222 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.67 (1884042402 / 1890333858)
00:25:57.0037 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.67 (1884042402 / 1890333858)
00:25:58.9011 [INFO] SteamCMD: Success! App '298740' fully installed.
00:25:59.6111 [INFO] SteamCMD: Redirecting stderr to 'E:\se\ds\torch-server\steamcmd\logs\stderr.txt'
00:25:59.7146 [INFO] Initializer: Generating default config at E:\se\ds\torch-server\Torch.cfg
00:26:00.0554 [FATAL] Initializer: System.MissingFieldException: Field not found: 'Sandbox.Engine.Utils.MyFakes.ENABLE_INFINARIO'.
   at Torch.Server.TorchServer..ctor(TorchConfig config)
   at Torch.Server.Initializer.Run() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Initializer.cs:line 85
   at Torch.Server.Program.Main(String[] args) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Program.cs:line 62

**Comment by Jimmacle** [comment]
See #176
