### ISSUE TITLE
[FATAL] Initializer: System.MissingFieldException: Field not found: 'Sandbox.Engine.Utils.MyFakes.ENABLE_INFINARIO'.

### ISSUE THREAD

**Issue by ironphildo69** [TorchAPI/Torch#179]
- [X] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [X] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.2.0 **SE Version:** 1.185.2

### Expected Behavior
What did you expect to happen?

Torch to initialize and start

### Observed Behavior
What actually happened?

Error thrown after successfully updating steamcmd and Space Engineers.

### Steps to Reproduce
1. How did this issue get triggered?

By starting torch in a Windows Server 2016 Core environment. No deviation from standard install.

2. Write the steps here.

Start Torch from a empty directory with the latest build files only.
Error will occur after torch updates steamcmd and downloads SE.
I would say the error occurs when torch begins to start the server.

### Other Information
Provide links to game logs or saves here if necessary.

12:32:49.4526 [FATAL] Initializer: System.MissingFieldException: Field not found: 'Sandbox.Engine.Utils.MyFakes.ENABLE_INFINARIO'.
   at Torch.Server.TorchServer..ctor(TorchConfig config)
   at Torch.Server.Initializer.Run() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Initializer.cs:line 85
   at Torch.Server.Program.Main(String[] args) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Program.cs:line 62

**Comment by Jimmacle** [comment]
Get the latest version.

**Comment by ironphildo69** [comment]
My apologies but based on the available builds 1.2.0 is the latest avaliable

![image](https://user-images.githubusercontent.com/11908363/33521523-da83e104-d827-11e7-92e6-dd6603134445.png)

If this is incorrect please let me know

**Comment by ironphildo69** [comment]
ahh, nevermind, my apologies, im a fool. didnt see the 1.3 release
