### ISSUE TITLE
No WPF UI Context available for plugins until the user selects the specific plugin from the tab

### ISSUE THREAD

**Issue by Phoenix84** [TorchAPI/Torch#180]
This is an issue with the Plugin API.

**Torch Version:** 1.3.0.8 **SE Version:** 1.185.401

### Expected Behavior
Torch plugin should have access to UI dispatcher without having to switch to the plugin page.

### Observed Behavior
IWpfPlugin.GetControl() isn't called until you select the specific plugin from the Plugin tab.

### Steps to Reproduce
Create a plugin that implements IWpfPlugin.
Add a MessageBox to GetControl()
Notice that if you just launch torch and start the server, the MessageBox is never displayed.
However if you select the plugin, the messagebox is shown.

### Other Information
This is the only way to get UI context information from torch, in case the plugin needs to open a separate form, or message box (because the Dispatcher is required since the plugins don't run in the UI thread). This could happen at any time during the plugin lifetime. Currently this requires the server admin/user to select the plugin from the list, before any prompts might appear.

The solution to this doesn't require GetControls to be called at startup. The TorchBase just needs to expose the UI Dispatcher.

**Comment by Jimmacle** [comment]
Fixed a while ago, forgot to close.
