### ISSUE TITLE
Suggestion: Cleanup delete subtype and type commands to delete single blocks.

### ISSUE THREAD

**Issue by XeroCreator** [TorchAPI/Torch#182]
- [X] Is this a suggestion?
Suggestion: 
need command for !cleanup delete subtype <blocksubtypeid>
and if possible and not too hard !cleanup delete type <blocktypeid>
This would essentially just delete type or subtype id of all blocks in the world matching the type/subtype ids

example:
!cleanup delete type Projector
!cleanup delete subtype LargeProgrammableBlock

**Comment by N1Ran** [comment]
!blocks does this now.  Closing
