### ISSUE TITLE
Text wrap on Chat/Players tab not working.

### ISSUE THREAD

**Issue by szczepix** [TorchAPI/Torch#186]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.0.9 **SE Version:** 1.185.700

### Expected Behavior
Text wrap on `Chat/Players` tab.

### Observed Behavior
Text not wrap.
![Chat Tab](https://i.imgur.com/xG7Jnak.png)

### Steps to Reproduce
Type a lot of words on chat.

**Comment by Jimmacle** [comment]
Fixed a while ago, forgot to close the issue.
