### ISSUE TITLE
Needed Features for Server Hosts.

### ISSUE THREAD

**Issue by Neimoh** [TorchAPI/Torch#188]
FEATURE REQUEST - These are all screenshots from SESE and Essentials with all their features and options. I would like to push forward again triggered cleanups, a much more useful entity manager with live import/export. Ability to change grid position, owner, edit storage contents, set static, alter speed and manipulate blocks on/off, lock/unlock for landing gear. Also the ability to modify factions. These I feel are all critical options needed for a host to properly run a server for their community. The simple act of changing ownership or locating a lost grid or restoring a grid for a member involves actually shutting the server down which should not be needed as it was not needed in the past with SESE.
![custommotd](https://user-images.githubusercontent.com/18516318/35024045-7f69f69e-fb0b-11e7-80d9-41a2a8798102.JPG)
![entitylist1](https://user-images.githubusercontent.com/18516318/35024047-83e0bed8-fb0b-11e7-9bc3-eb2718841a2e.JPG)
![entitylist2](https://user-images.githubusercontent.com/18516318/35024050-86515538-fb0b-11e7-8f43-8e2e7c2fc510.JPG)
![essentials1](https://user-images.githubusercontent.com/18516318/35024051-88331350-fb0b-11e7-8d46-af82b86acd53.JPG)
![essentials2](https://user-images.githubusercontent.com/18516318/35024053-8a43051a-fb0b-11e7-9800-6e1136438797.JPG)
![essentials3](https://user-images.githubusercontent.com/18516318/35024056-8c844c08-fb0b-11e7-9338-9066eafa9211.JPG)
![factiontab](https://user-images.githubusercontent.com/18516318/35024061-8f7b70c6-fb0b-11e7-9136-5a02d7dc7652.JPG)
![protection1](https://user-images.githubusercontent.com/18516318/35024065-924e00a2-fb0b-11e7-83c9-a645d41b9627.JPG)
![protection2](https://user-images.githubusercontent.com/18516318/35024067-9437e27a-fb0b-11e7-85a3-b9023b56e7b6.JPG)
![triggeredcleanup](https://user-images.githubusercontent.com/18516318/35024068-95d96e0a-fb0b-11e7-92c1-f4b630b92661.JPG)

**Comment by szczepix** [comment]
We very much need this features

**Comment by Murllin** [comment]
Very much loved these features. Much needed

**Comment by GRUBAcoin** [comment]
Check AVORION game https://www.avorion.net/ = This is space engineers ,  eve online, empyrion. and no micropay, no online abonament etc.. this is normal GAME !!  Space engineers is shit for me ;/ . Sorry guys.

**Comment by Jimmacle** [comment]
@GRUBAcoin For future reference, this isn't the place to shill for other games. If you hate SE go send Keen an e-mail, I don't care.

**Comment by pa0l0s** [comment]
Those would be very useful

**Comment by Equinox-** [comment]
Closing in favor of more organized issues.
