### ISSUE TITLE
Entity Manager Grid Main View

### ISSUE THREAD

**Issue by Neimoh** [TorchAPI/Torch#191]
- [ ] 'Grid block count'
- [ ] 'EntityID'
- [ ] 'Grid Size' large/small
- [ ] 'Mass'
- [ ] 'Grid Name' and able to change
- [ ] 'Current GPS' view and be able to key in new cords x:y:z to move it
- [ ] 'Speed'
- [ ] 'Static' true/false option to change
- [ ] 'Concealed <physics> status' I believe it was InScene
- [ ] 'BigOwners' - view
- [ ] 'MajorityOwner' - view/alter
- [ ] 'SmallOwners' -view list

**Comment by rexxar-tc** [comment]
Add grouping by physical grid groups
