### ISSUE TITLE
Entity Manager General

### ISSUE THREAD

**Issue by Neimoh** [TorchAPI/Torch#193]
Ability to sort grid list by Display Name, Owner Name <majority owner>, Block Count, Distance from Center, Mass, Speed, Size < large grid or small grid >
 Import / Export grids

**Comment by zenduin** [comment]
I would be happy with just SOME kind of sorting... Manually looking through 200+ grids to find the one you're looking for is just horrible.
Also I miss import/export SOOO much. It would be cool if there were collision checking on import too (following the theme of improving SESE).

**Comment by Ryan-Battersby** [comment]
hello, I have noticed that the entity manager does not show the number of Grids, Characters, Voxel Maps & Floating obkects. I noticed this broke probabyly 2 or 3 updates ago?


https://gyazo.com/e8b484012ff95d40ea2044bebe9d6dc8
