### ISSUE TITLE
Faction Manager

### ISSUE THREAD

**Issue by Neimoh** [TorchAPI/Torch#194]
List of all Factions and ability to delete factions
Faction view should have:
Description view/edit
PrivateInfo view/edit
Founder
FactionName
Tag
Acceptall
AcceptHumans
AcceptPeace
FriendlyFire

Should be able to see Active members and Join requests with ability to Kick members, Promote and accept requests

**Comment by szczepix** [comment]
and maybe add `Bot` to faction

**Comment by zenduin** [comment]
I would happy with a !factions clean command to remove the factions with no members honestly...

**Comment by Branakburn** [comment]
WOW YES

**Comment by Alliguierg** [comment]
Nice seggestion

**Comment by FabioZumbi12** [comment]
I think this can be done via plugin...
