### ISSUE TITLE
[User Story] Main Window Improvements

### ISSUE THREAD

**Issue by Jonathan-Rosewood** [TorchAPI/Torch#196]
**As a**
Server Owner

**I want** 
See the number of players on the server on the main window

**So that** 
Visually represent the possible load and current server popularity

![example](https://image.prntscr.com/image/KkiCkAX7QXO1CLInsi-NEA.png)

P.S. English is not my native language and I do not know it well. In advance I apologize for the awkwardness of the translation.

**Comment by Jimmacle** [comment]
This was added at some point and we never closed the issue.
