### ISSUE TITLE
Trying to load Torch

### ISSUE THREAD

**Issue by Kurtz31000** [TorchAPI/Torch#206]
**Torch Version:** 1.x.xxx.xxx **SE Version:** 1.xxx.xxx

### Observed Behavior
I am trying to start Torch Server (Latest version 1.3.0.21) but this error appears : 

> 18:05:23.0016 [INFO]   SteamCMD: Checking for DS updates.
> 18:05:23.1827 [INFO]   SteamCMD: Redirecting stderr to 'D:\T??l??chargements\torch-server\steamcmd\logs\stderr.txt'
> 18:05:23.2848 [INFO]   Initializer: Generating default config at D:\Téléchargements\torch-server\Torch.cfg
> 18:05:23.2958 [FATAL]  Initializer: System.IO.FileNotFoundException: Impossible de charger le fichier ou l'assembly 'VRage.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ou une de ses dépendances. Le fichier spécifié est introuvable.
> Nom de fichier : 'VRage.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
>    à Torch.CommandLine..ctor(String argPrefix)
>    à Torch.Server.TorchConfig..ctor(String instanceName, String instancePath)
>    à Torch.Server.Initializer.InitConfig()
>    à Torch.Server.Initializer.Initialize(String[] args)
>    à Torch.Server.Program.Main(String[] args)
>    à System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
>    à System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
>    à Torch.Utils.TorchLauncher.Launch(String entryPoint, String[] args, String[] binaryPaths)
>    à Torch.Server.Program.Main(String[] args)
> 
> Gestionnaire des assemblys chargé à partir de :  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
> Exécution sous l'exécutable  D:\Téléchargements\torch-server\Torch.Server.exe
> --- Un journal des erreurs détaillé suit.
> 
> === Informations d'état de liaison préalable ===
> JRN : DisplayName = VRage.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
>  (Fully-specified)
> JRN : Appbase = file:///D:/Téléchargements/torch-server/
> JRN : PrivatePath initial = d:\téléchargements\torch-server;d:\téléchargements\torch-server\dedicatedserver64
> Assembly appelant : Torch, Version=1.3.0.21, Culture=neutral, PublicKeyToken=null.
> ===
> JRN : cette liaison démarre dans le contexte de chargement de default.
> JRN : utilisation du fichier de configuration de l'application : D:\Téléchargements\torch-server\Torch.Server.exe.Config
> JRN : utilisation du fichier de configuration d'hôte :
> JRN : utilisation du fichier de configuration de l'ordinateur à partir de C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
> JRN : stratégie non appliquée à la référence à ce stade (liaison d'assembly privée, personnalisée, partielle ou basée sur l'emplacement).
> JRN : tentative de téléchargement de la nouvelle URL file:///D:/Téléchargements/torch-server/VRage.Library.DLL.
> JRN : tentative de téléchargement de la nouvelle URL file:///D:/Téléchargements/torch-server/VRage.Library/VRage.Library.DLL.
> JRN : tentative de téléchargement de la nouvelle URL file:///d:/téléchargements/torch-server/dedicatedserver64/VRage.Library.DLL.
> JRN : tentative de téléchargement de la nouvelle URL file:///d:/téléchargements/torch-server/dedicatedserver64/VRage.Library/VRage.Library.DLL.
> JRN : tentative de téléchargement de la nouvelle URL file:///D:/Téléchargements/torch-server/VRage.Library.EXE.
> JRN : tentative de téléchargement de la nouvelle URL file:///D:/Téléchargements/torch-server/VRage.Library/VRage.Library.EXE.
> JRN : tentative de téléchargement de la nouvelle URL file:///d:/téléchargements/torch-server/dedicatedserver64/VRage.Library.EXE.
> JRN : tentative de téléchargement de la nouvelle URL file:///d:/téléchargements/torch-server/dedicatedserver64/VRage.Library/VRage.Library.EXE.
> 
> System.IO.FileNotFoundException: Impossible de charger le fichier ou l'assembly 'VRage.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ou une de ses dépendances. Le fichier spécifié est introuvable.
> Nom de fichier : 'VRage.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
>    à Torch.CommandLine..ctor(String argPrefix)
>    à Torch.Server.TorchConfig..ctor(String instanceName, String instancePath)
>    à Torch.Server.Initializer.InitConfig()
>    à Torch.Server.Initializer.Initialize(String[] args)
>    à Torch.Server.Program.Main(String[] args)
>    à System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
>    à System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
>    à Torch.Utils.TorchLauncher.Launch(String entryPoint, String[] args, String[] binaryPaths)
>    à Torch.Server.Program.Main(String[] args)
> 
> Gestionnaire des assemblys chargé à partir de :  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
> Exécution sous l'exécutable  D:\Téléchargements\torch-server\Torch.Server.exe
> --- Un journal des erreurs détaillé suit.
> 
> === Informations d'état de liaison préalable ===
> JRN : DisplayName = VRage.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
>  (Fully-specified)
> JRN : Appbase = file:///D:/Téléchargements/torch-server/
> JRN : PrivatePath initial = d:\téléchargements\torch-server;d:\téléchargements\torch-server\dedicatedserver64
> Assembly appelant : Torch, Version=1.3.0.21, Culture=neutral, PublicKeyToken=null.
> ===
> JRN : cette liaison démarre dans le contexte de chargement de default.
> JRN : utilisation du fichier de configuration de l'application : D:\Téléchargements\torch-server\Torch.Server.exe.Config
> JRN : utilisation du fichier de configuration d'hôte :
> JRN : utilisation du fichier de configuration de l'ordinateur à partir de C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
> JRN : stratégie non appliquée à la référence à ce stade (liaison d'assembly privée, personnalisée, partielle ou basée sur l'emplacement).
> JRN : tentative de téléchargement de la nouvelle URL file:///D:/Téléchargements/torch-server/VRage.Library.DLL.
> JRN : tentative de téléchargement de la nouvelle URL file:///D:/Téléchargements/torch-server/VRage.Library/VRage.Library.DLL.
> JRN : tentative de téléchargement de la nouvelle URL file:///d:/téléchargements/torch-server/dedicatedserver64/VRage.Library.DLL.
> JRN : tentative de téléchargement de la nouvelle URL file:///d:/téléchargements/torch-server/dedicatedserver64/VRage.Library/VRage.Library.DLL.
> JRN : tentative de téléchargement de la nouvelle URL file:///D:/Téléchargements/torch-server/VRage.Library.EXE.
> JRN : tentative de téléchargement de la nouvelle URL file:///D:/Téléchargements/torch-server/VRage.Library/VRage.Library.EXE.
> JRN : tentative de téléchargement de la nouvelle URL file:///d:/téléchargements/torch-server/dedicatedserver64/VRage.Library.EXE.
> JRN : tentative de téléchargement de la nouvelle URL file:///d:/téléchargements/torch-server/dedicatedserver64/VRage.Library/VRage.Library.EXE.
> 
> 
> Exception non gérée : System.IO.FileNotFoundException: Impossible de charger le fichier ou l'assembly 'VRage.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ou une de ses dépendances. Le fichier spécifié est introuvable.
>    à Torch.CommandLine..ctor(String argPrefix)
>    à Torch.Server.TorchConfig..ctor(String instanceName, String instancePath)
>    à Torch.Server.Initializer.InitConfig()
>    à Torch.Server.Initializer.Initialize(String[] args)
>    à Torch.Server.Program.Main(String[] args)
>    à System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
>    à System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
>    à Torch.Utils.TorchLauncher.Launch(String entryPoint, String[] args, String[] binaryPaths)
>    à Torch.Server.Program.Main(String[] args)
> 

I have never tried this program, I have a dedicated server on space engineers...

**Comment by Jimmacle** [comment]
It looks like SteamCMD failed to download the vanilla server files properly before Torch tried to use them. Not surprising because SteamCMD is hot garbage but until there's something better you'll just have to mess with it until it works.

**Comment by Jimmacle** [comment]
Closing due to no response, please re-open the issue if you're still having problems.
