### ISSUE TITLE
MOTD doesn't appear on player login.

### ISSUE THREAD

**Issue by Inoram** [TorchAPI/Torch#210]
MOTD doesn't appear on player login.

2-22-18 version of Torch and 2-26-18 version of Essentials
no other plugin installed.

**Comment by foogs** [comment]
they not appear if steam hud disabled too :shipit:

**Comment by Jimmacle** [comment]
Should be fixed https://github.com/TorchAPI/Essentials/commit/aa2d1d2d325f67e58a5724326804cb2a6c5a2ff2
