### ISSUE TITLE
!restart works intermittently in the chat bar

### ISSUE THREAD

**Issue by Inoram** [TorchAPI/Torch#212]
I was waiting until I report this one to try to get better information, but I really don't have any. Sometimes !restart works and sometimes after the !restart  Torch just sits there not doing anything. No error, nothing.

I have seen it with !restart, !restart 20, !restart 600.

I am not sure if this is the same as if run in the AutoCommands, I have not tried that yet.

Torch v1.3.0.27-49-ge72f5b7
Essentials v1.7.0.13-4-g83ada5b

no other plug ins

**Comment by Murllin** [comment]
I’ve seen it do this as well I’m curious how long have you waited and watched it to see what it does. My server will have a good minute or two of nothing but then it will eventually close out all the grids and stop. But it’s almost as if it’s haveing trouble removing any current players from the world. My server has about 900 grids and 7000 asteroids so it takes some time to shut down.

**Comment by Inoram** [comment]
3-5 minutes roughly. ~200 grids.~450 asteroids, no players.

**Comment by Murllin** [comment]
So it closes after 3-5 minutes or you lose patience and exit out after 3-5 minutes?

**Comment by Inoram** [comment]
Lose patience.

**Comment by Inoram** [comment]
I tried it again, it sat for 11 minutes and then someone joined and it appeared like someone joining triggered it to restart.

**Comment by Cabub** [comment]
I've also got this issue as well, my suspicion is that the command won't run while the server is paused, and you have the config 'Pause When Empty' turned on, as I do. I can run without that config today and report my findings.

**Comment by Jimmacle** [comment]
Hm, I guess that option completely pauses the update loop so when we invoke code on the game thread it never gets to it until someone joins the server. I can't think of an easy fix at the moment but if you're running Concealment the server is effectively paused when nobody is online anyway so you might be able to avoid using the option until we figure it out.
