### ISSUE TITLE
[Feature Request] Restore lost grids from cleanup

### ISSUE THREAD

**Issue by Neimoh** [TorchAPI/Torch#213]
Ability for a player to restore a grid lost due to a cleanup. Player needs to be able to get a list of their deleted grids in the last 24hrs or a host defined time period and choose which ones to restore. A possible option to enable and define cool down periods to prevent abuse as well.

**Comment by Branakburn** [comment]
Please make this a priority, This would be terribly helpful for SE admins!
This would save so much Time!

**Comment by zader64** [comment]
I really cant believe this is not a vanilla option.
