### ISSUE TITLE
[Feature Request] Edit contents of block inventories

### ISSUE THREAD

**Issue by Neimoh** [TorchAPI/Torch#215]
Can we get the options to view/add/remove items from entity block inventories? We can see the blocks just not whats in them. 
Also edit player inventories

**Comment by Branakburn** [comment]
Please make this a priority, This would be terribly helpful for SE admins!

**Comment by zader64** [comment]
I remember when I would randomly insert surprises in the containers of those who pleased me back on PHOBOS

**Comment by TLawV01** [comment]
+1
