### ISSUE TITLE
Low simspeed on 6+ players (Powerful server)

### ISSUE THREAD

**Issue by MrBenFTW** [TorchAPI/Torch#216]
Hello, I am hosting a big server (12 mods). We constantly have 10+ players. It gets very laggy. 

Server specs: Dedicated OVH server
6900k (no OC)
64GB DDR4
480GB SSD
1000/1000mbps

Game runs fine at a stable 1 sim speed when theres up to 6 people online. Anymore and the simspeed suffers. I doubt it is todo with the hardware and more the game. 

I have Essentials, Concealment and profiler installed. 

Are there any recommendations on how to improve simspeed? I am thinking it is to do with bandwidth. We have 1000/1000mbps but I don't think space engineers is taking advantage of it and thus suffering to keep up. Is there any plugins to change bandwith? Kind of like you can do with Arma3? 

Thanks.

**Comment by Jimmacle** [comment]
This is an issue with multiplayer replication performance that Keen is looking into fixing.
