### ISSUE TITLE
 Torch does not respond to commands in the chat -! Cleanup scan notype Beacon,! Cleanup delete notype Beacon,! Cleanup scan notype beacon,! Cleanup delete notype beacon ...  MOTD - does not display a window at the start of the game when the player hops.

### ISSUE THREAD

**Issue by homemonster** [TorchAPI/Torch#224]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.x.xxx.xxx **SE Version:** 1.xxx.xxx

### Expected Behavior
What did you expect to happen?

### Observed Behavior
What actually happened?

### Steps to Reproduce
1. How did this issue get triggered?
2. Write the steps here.

### Other Information
Provide links to game logs or saves here if necessary.

**Comment by Jimmacle** [comment]
Please format your issue correctly and reopen it.
