### ISSUE TITLE
[Feature] World Save archiving and purge

### ISSUE THREAD

**Issue by Neimoh** [TorchAPI/Torch#225]
I'm looking at SE auto-saves taken every 10 minutes and only keeping 25 of them on a server I'm hosting. That folder is 5gigs only with 25 auto-saves. 
I pulled up my old server extender archives and I was able to take a backup every 30 minutes all day long which auto-zipped then retain 30 days of those backups. A single days worth of backups were around 420mb and the entire months worth was about 19gb.

SE's method of backing up is beyond sub-par, I'd like to see Torch either take it's own world backups or monitor the instance backup folder for keens backup to hit then compress that folder and delete the original then purge those compressed files after so many days old at a bare minimum. The option to define a custom location for those archived files would be nice to have in the case we're running the server on a small ssd and have a much larger mechanical hdd we can store those on.

**Comment by Jimmacle** [comment]
Someone wrote a backup plugin already, does this do what you want? https://github.com/sirhamsteralot/TorchBackupSystem/releases

**Comment by Neimoh** [comment]
I’m testing this plugin now, but with some help we created a batch file running from a windows task every 30 minutes to do everything I want with backups.

Sent from Mail for Windows 10

**Comment by Neimoh** [comment]
This does not compress the backups. It gives you the option to relocated keens backups and it basically copies the world folder contents to where you specify.

I have a batch file that copies the sandbox files and planet files and the \save\storage\ contents to a backup location named via date/time stamp on another drive zip those files up via WinRAR deleting the originals and that folder then checking if any files are older than 30 days and deleting those. This is running on a windows task every 30 minutes. 
It would be very nice if torch would do all that as my backup files have been reduced from several hundred megs to a mere 12mb per zip.

Sent from Mail for Windows 10

**Comment by rexxar-tc** [comment]
I'm implementing everything on hamster's plugin.
