### ISSUE TITLE
[Feature Request] Whitelist PB scripts

### ISSUE THREAD

**Issue by Neimoh** [TorchAPI/Torch#230]
Per a conversation with Jimmacle could we have the ability to define a PB script whitelist or blacklist where we specify specific scripts to be allowed to run on the server and block all others from running.

**Comment by Alliguierg** [comment]
It will be a very useful function. Please implement this.

**Comment by szczepix** [comment]
Scripts dead servers sometimes... Please implement this soon as possible 😉

**Comment by N1Ran** [comment]
A plugin already exist for this.  Please close

**Comment by Sipowicz** [comment]
The existing Plug-in for this does not work.
