### ISSUE TITLE
Torch Crash on Import world config.

### ISSUE THREAD

**Issue by ProsperCraft** [TorchAPI/Torch#231]
**Torch Version:** v1.3.0.42-84-gd8915d1 -- | --  **SE Version:** 1.186.5

### Observed Behavior
What actually happened?
Torch crashed when clicking get world config when no world is selected.

### Other Information
Provide links to game logs or saves here if necessary.

Log with crash info at the bottom.
https://gist.github.com/ProsperCraft/4c9e3044492c511950ae534b19509b0e

**Comment by SinZ163** [comment]
Still present in v1.3.0.43-85-g9286f2e | 1.186.500

https://gist.github.com/SinZ163/3e7c77ce70b8481c41487cae8fe0d3d6

**Comment by Jimmacle** [comment]
Temporary solution: Don't click that button when you don't have a world selected.
