### ISSUE TITLE
Description bouncing

### ISSUE THREAD

**Issue by Jonathan-Rosewood** [TorchAPI/Torch#240]
**Torch Version:** v1.3.0.55-129-g14e16a9 **SE Version:** 1.187.89

![gif](https://i.imgur.com/2ewmPlX.gif)

**Comment by Jimmacle** [comment]
I actually fixed this yesterday, I just haven't pushed it since I'm still making some UI improvements. SoonTM

**Comment by Jimmacle** [comment]
Should be fixed in 5bf91f189154aa6e65546fa5be30d904c3e26736
