### ISSUE TITLE
chat system doesnt allow GPS posting

### ISSUE THREAD

**Issue by 2073** [TorchAPI/Torch#243]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [x] Is this a suggestion?

**Torch Version:** 1.x.xxx.xxx **SE Version:** 1.xxx.xxx

### Expected Behavior
Used the "!say" command to send coordinates to the server and have them show in player GPS same as when a player post in global chat

### Observed Behavior
Did not show in GPS only in Global chat

**Comment by rexxar-tc** [comment]
Requires an additional module in Torch Client mod. Should probably route all chat through the mod instead of relying on visual scripting methods.
