### ISSUE TITLE
Suggestion; New vanilla features

### ISSUE THREAD

**Issue by Fowlplaychiken** [TorchAPI/Torch#245]
There are two reasonably minor features from the new Vanilla SE manager that I really miss after switching to torch;

1) Their new Vanilla entity list allows one to sort entity by size, speed, owner, etc; very useful for a number of things.  This is the big one and is sorely missed.

2) being able to promote/demote players via the Manager. When a grid becomes bugged in SE, if no admin online I usually temporarily promote someone ‘trusted’ via the client so that they can cut/paste the glitched grid. Then demote them again when task complete. When I am not home/cant be in game and am using Teamviewer via my phone, this is a very helpful feature.

**Comment by rexxar-tc** [comment]
Promote/demote implemented. Entity list sorting is duplicated by #193
