### ISSUE TITLE
[FR] Windows EVENT IDs to trigger actions through windows

### ISSUE THREAD

**Issue by Varaxian** [TorchAPI/Torch#248]
**SUMMARY**

If a list of TORCH EVENT IDs are available (or if its utilizing .NET error IDs), actions can be triggered (such as webhook alerts) for when the server throws an error, thus minimizing the collateral damage by alerting server-admins of the error immediately.

**Comment by Varaxian** [comment]
For instance:

The errors listed in Torch.API.xml

        <member name="F:Torch.API.ServerState.Error">
            <summary>
            The server encountered an error.
            </summary>

Is it possible to have these events show in Windows Event Viewer?

**Comment by Jimmacle** [comment]
Looks like it's possible, going to leave this here for future reference: https://stackoverflow.com/questions/25725151/write-to-windows-application-event-log
