### ISSUE TITLE
DS crashes after player interacts with world

### ISSUE THREAD

**Issue by everwake242** [TorchAPI/Torch#249]
Torch Version: v1.3.0.61-135-g65e8d62
Problem also verified 
in torch 1.3.0.59
Game Version: 1.187.101

### Expected Behavior

Not crashing

### Observed Behavior

DS crashed within a few minutes of player joining

### Steps to Reproduce
somewhat random, but usually happens in a few minutes after joining when interacting with voxels or blocks. simly flying around in the lander without touch ground or using tools I have not been able to reproduce the crash.

2. Write the steps here.
join in, try to land lander on earth, touching the earth, using welders or grinders usually triggers it.

### Other Information
Have tried a vanilla starter system with no mods, same result as a modded world, running the same savegame in the standard spaceengineers DS server does not result in crash.

Several world saves tried with same result, same worlds run stable in vanilla DS for hours.
Keen-log show no entries related to the crash and restart, Torch log attached.
[torch_log_extract.txt](https://github.com/TorchAPI/Torch/files/2270336/torch_log_extract.txt)

**Comment by szczepix** [comment]
Have you right setup to Instance directory?

**Comment by everwake242** [comment]
I don't know what you mean? I have copied in a save game and .cfg file, and I can login to the server and fly around, what could be wrong in instance directory?

**Comment by Fowlplaychiken** [comment]
Disable concealment until its fixed

**Comment by everwake242** [comment]
actuallt disabling concealment had no effect, it crashed 10s after I joing the world with the same error

**Comment by everwake242** [comment]
The problem was related to block limits, not concealment, removing block limits made it work
