### ISSUE TITLE
Wrong time format

### ISSUE THREAD

**Issue by Fank** [TorchAPI/Torch#257]
- [X] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [X] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [X] Is this a suggestion?

**Torch Version:** 1.3.0.68-143-g0ff715a **SE Version:** 1.187.205

### Expected Behavior
Day (1+)
Hour (2)
Minutes (2)
Seconds (2)

### Observed Behavior
![image](https://user-images.githubusercontent.com/1900106/45329126-345f9500-b55f-11e8-820d-87f5aebc6b71.png)

### Steps to Reproduce
Run a server more then 1 day

### Other Information
Provide links to game logs or saves here if necessary.

**Comment by rexxar-tc** [comment]
What exactly is the problem here?

**Comment by Fank** [comment]
I want hours shown in 2 numbers, instead of 1

**Comment by Jimmacle** [comment]
It will show it in 2 numbers if the number is 2 digits. I don't consider this to be an issue.
