### ISSUE TITLE
Main window not remembering it's location

### ISSUE THREAD

**Issue by Thraxus** [TorchAPI/Torch#260]
- [X] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [X] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [Maybe?] Is this a suggestion?

**Torch Version:** 1.3.0.67-142-ga318aa8 **SE Version:** 1.187.209

### Expected Behavior
Window remembers location on close

### Observed Behavior
Window constantly starts top left

### Steps to Reproduce
Open Torch - it starts top left of the main screen
Move Window to some other position
Close Torch
Open Torch - it's back at the top left

### Other Information
If this is intended behavior, an option to start center screen would be helpful.  Some of us relocate our taskbar, and this ends up shoving the client under mine, so I have to unlock / move it to get the window back in a serviceable position (am on a remote connection to my test server, so winkey+arrows isn't always an option).

**Comment by rexxar-tc** [comment]
Hey @Jimmacle fun fact, the XML serializer can't serialize internal properties. Maybe don't do that? idk
