### ISSUE TITLE
Change GC mode to server

### ISSUE THREAD

**Issue by Fank** [TorchAPI/Torch#261]
- [X] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [X] Is this a suggestion?

Current server uses Workstation mode -> concurrent i recommend to change it to server mode
https://stackoverflow.com/questions/9669963/monitoring-garbage-collector-in-c-sharp

**Comment by Equinox-** [comment]
We aren't going to disable concurrent GC collections or move to a server GC.  Both would only increase stutters due to GC pressure.
