### ISSUE TITLE
Playtest Checkbox and Feature Additions

### ISSUE THREAD

**Issue by flamepyro** [TorchAPI/Torch#273]
**Suggestion**

_Checkboxes to add into Torch:_

Enable Research
Enable Good.bot Hints

_Native to Vanilla but in Essentials or another plugin:_
MOTD
Message of the Day URL
Auto restart - Would like to see the ability to add torch to a service like SE dedicated can so if the computer reboots it would still launch without having an additional batch file. Also don't know if we could add in a monitor for crashing as well.
Auto Update - included in the launcher anyway but something that polls for update and initiates a Notification that the server will be down in X mins and does a reboot to update files.

**Comment by szczepix** [comment]
Check this: http://topshelf-project.com/

**Comment by szczepix** [comment]
Check this: http://topshelf-project.com/ for Windows Service
and this: https://github.com/Squirrel/Squirrel.Windows for AutoUpdate

**Comment by Jimmacle** [comment]
All of this looks implemented by now
