### ISSUE TITLE
[Suggestion] Plugin API for manipulating (injecting into) mod list.

### ISSUE THREAD

**Issue by theCalcaholic** [TorchAPI/Torch#275]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Is this a suggestion?

For plugin development, it would be handy to have an API for injecting mods into the mod list. This enables plugins to affect certain client aspects as for example the terminal block UI.

**Comment by rexxar-tc** [comment]
Done on Patron branch
