### ISSUE TITLE
[Suggestion] SMTP or SMS Alerts

### ISSUE THREAD

**Issue by SovereignR0B** [TorchAPI/Torch#276]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [X ] Is this a suggestion?

Anyone interested in putting together a plugin or addition that sends an e-mail when there is a crash/problem or SMS? 

Or SEDISCORDBRIDGE send a private message to a user on the event of a crash or problem? Discuss?

**Comment by Jimmacle** [comment]
This should be resubmitted as a plugin request on Discord if it's still wanted
