### ISSUE TITLE
Modify the mod tab to allow adding a list of mods at once

### ISSUE THREAD

**Issue by Jimmacle** [TorchAPI/Torch#277]
Modify this area to a multiline text box, make a pop-up dialog, etc. to make it easier to add a collection of mods stored in a text file or similar

![image](https://user-images.githubusercontent.com/6447556/52166965-1ee33700-26c9-11e9-899d-3880c07e7ca6.png)

**Comment by Mr-Mors** [comment]
Please! I love the new interface, but I use excel to keep my mods strait across servers and such and just used to drop a long list of mods in the mod field.

**Comment by rexxar-tc** [comment]
Done on Patron branch
