### ISSUE TITLE
TorchMod critical errors

### ISSUE THREAD

**Issue by szczepix** [TorchAPI/Torch#278]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** v1.3.1.13-11-g61307ce **SE Version:** 1.88.105

### Expected Behavior
TorchMod loading fully without errors.

### Observed Behavior
TorchMod have critical error when loading.

### Steps to Reproduce
1. Download and setup newest Torch Server
2. Create empty world.
3. Start server.
4. Join to server.

### Other Information
```MOD_CRITICAL_ERROR: TorchMod, in file: 
MOD PARTIALLY SKIPPED, LOADED ONLY 1/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)
MOD_CRITICAL_ERROR: TorchMod, in file: 
MOD PARTIALLY SKIPPED, LOADED ONLY 2/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)
MOD_CRITICAL_ERROR: TorchMod, in file: 
MOD PARTIALLY SKIPPED, LOADED ONLY 3/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)
MOD_CRITICAL_ERROR: TorchMod, in file: 
MOD PARTIALLY SKIPPED, LOADED ONLY 4/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)
MOD_CRITICAL_ERROR: TorchMod, in file: 
MOD PARTIALLY SKIPPED, LOADED ONLY 5/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)
MOD_CRITICAL_ERROR: TorchMod, in file: 
MOD PARTIALLY SKIPPED, LOADED ONLY 6/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)```

**Comment by szczepix** [comment]
![image](https://user-images.githubusercontent.com/1363477/52457697-8979f400-2b5b-11e9-92ed-25d599f4d973.png)
![image](https://user-images.githubusercontent.com/1363477/52457715-9991d380-2b5b-11e9-8ca3-d7e0b5747216.png)

**Comment by szczepix** [comment]
![image](https://user-images.githubusercontent.com/1363477/52457890-669c0f80-2b5c-11e9-9366-fff1f7785b26.png)
[SpaceEngineers.log](https://github.com/TorchAPI/Torch/files/2843549/SpaceEngineers.log)
[Torch-Logs.zip](https://github.com/TorchAPI/Torch/files/2843551/Torch-Logs.zip)

**Comment by szczepix** [comment]
[Torch-Instance.zip](https://github.com/TorchAPI/Torch/files/2843555/Torch-Instance.zip)

**Comment by szczepix** [comment]
Error view when a game is without Bin64_Profile files - just plain SE:
![image](https://user-images.githubusercontent.com/1363477/52458308-f8a51780-2b5e-11e9-983c-aa61008bdcf0.png)

**Comment by szczepix** [comment]
Custom World ingame with mod from Workshop: https://steamcommunity.com/sharedfiles/filedetails/?id=1406994352

![image](https://user-images.githubusercontent.com/1363477/52458499-fe4f2d00-2b5f-11e9-9c81-a75e2196c4c2.png)

**Comment by Jimmacle** [comment]
Keen isn't logging enough error information for me to debug this. Report it to them and see what they say.

**Comment by szczepix** [comment]
@Jimmacle reported to Keen's: https://support.keenswh.com/spaceengineers/general/topic/mods-not-load-properly

**Comment by rexxar-tc** [comment]
This is 100% a Keen error. The Torch Mod does not *have* any definitions to cause problems with the definition manager.
