### ISSUE TITLE
Request: Scripters textbox

### ISSUE THREAD

**Issue by Kothe** [TorchAPI/Torch#280]
Requesting a "Scripters" textbox to be added to the Configuration tab below the "Administrators" textbox and above the "Reserved Players" textbox.

Steam IDs listed here should be given the Scripter role in game automatically.

**Comment by szczepix** [comment]
You have buttons on the chat tab like a promote and demote. It's not enough?

**Comment by Kothe** [comment]
Sure, that's great when I'm in a position to wait for particular players to come online so I can jump on RDP and manually promote them one by one.

This requested functionality is mostly useful when you already know the people you want to give the Scripter role ahead of time - particularly in the instance of a new server going online or a world wipe.
