### ISSUE TITLE
Torch Theme has... some sort of issue on plugins tab.

### ISSUE THREAD

**Issue by XeroCreator** [TorchAPI/Torch#283]
- [ sure ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game

20:38:14.8253 [INFO]   Torch: Torch Version: v1.3.0.11-190-gac67209
20:38:14.8253 [INFO]   Torch: Game Version: 1.188.105

Torch dark theme doesn't work on specific plugins, could be related to the plugins but it happens everytime on restart.
https://cdn.discordapp.com/attachments/274308924273065985/546159698311905281/PB_Limiter_theme_messed_up.JPG
https://cdn.discordapp.com/attachments/274308924273065985/546159703856644116/essentials.JPG

If I go to themes, and reselect the theme(Dark Theme), the same plugins look fine.
https://cdn.discordapp.com/attachments/274308924273065985/546159751503937565/PB_Limiter_theme_fixed.JPG
https://cdn.discordapp.com/attachments/274308924273065985/546159758378532884/essentials_fixed.JPG

**Comment by Jimmacle** [comment]
Torch probably needs to reapply the theme after getting the plugin UI for the first time.
