### ISSUE TITLE
!restart does not restart empty server with "pause when empty"

### ISSUE THREAD

**Issue by everwake242** [TorchAPI/Torch#284]
when running !restart manually or scheduled the instance will not be restarted if there are no players logged in players and the server is set to "pause when empty".

When the first player logs in, the server will restart immediately:

**10:17:29.5955** [INFO]   Torch.Commands.CommandManager: Server ran command '!restart 0'
10:23:40.2779 [INFO]   Torch: Saved game    
**10:23:42.1763** [INFO]   Torch.Server.Managers.MultiplayerManagerDedicated: Connection attempt by XXXXXXXXXXXXXXX from 0  **<<<------ Player logs in**
10:23:42.4254 [INFO]   Torch: Saved game
10:23:42.4254 [INFO]   Torch: Stopping server.

**Comment by Mr-Mors** [comment]
Can confirm this behavior with my server as well.

**Comment by fly8oy** [comment]
Can confirm this issue is still happening
