### ISSUE TITLE
Independent Console Always Opens

### ISSUE THREAD

**Issue by Mr-Mors** [TorchAPI/Torch#285]
- [X ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [X ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.0.12-193 **SE Version:** 1.188.105

### Expected Behavior
With:
<IndependentConsole>false</IndependentConsole>

You should not have an independent console

### Observed Behavior
With no line or with the line listed above the independent console still opens.

### Steps to Reproduce
1. Update torch
2. Open torch.
3. No plugins loaded still has issue

### Other Information
No errors to report in log.

**Comment by rexxar-tc** [comment]
done

**Comment by Mr-Mors** [comment]
Issue is back in latest version of Patreon build.
