### ISSUE TITLE
world is set to offline and user is not admin.

### ISSUE THREAD

**Issue by elwiregiven** [TorchAPI/Torch#289]
Hi guys,

I've got a weird issue when i try to log to my server : 

09:50:29.6212 [WARN]   Torch.Server.Managers.MultiplayerManagerDedicated: Rejecting user 765611*****, world is set to offline and user is not admin.

Any clue ?

09:49:02.4364 [INFO]   Torch: Torch Version: v1.3.1.13-11-g61307ce
09:49:02.4364 [INFO]   Torch: Game Version: 1.188.105

**Comment by Jimmacle** [comment]
Set the world to online mode in the config.

**Comment by elwiregiven** [comment]
On what config file please ?

**Comment by Jimmacle** [comment]
Instance\SpaceEngineers-Dedicated.cfg

`<OnlineMode>PUBLIC</OnlineMode>`

**Comment by elwiregiven** [comment]
It's only set to PUBLIC :     

<RefinerySpeedMultiplier>3</RefinerySpeedMultiplier>
    <OnlineMode>PUBLIC</OnlineMode>
    <MaxPlayers>4</MaxPlayers>

**Comment by elwiregiven** [comment]
```
    <RefinerySpeedMultiplier>3</RefinerySpeedMultiplier>
    <OnlineMode>PUBLIC</OnlineMode>
    <MaxPlayers>4</MaxPlayers>
```

**Comment by Jimmacle** [comment]
You may have to change it in the save's `Sandbox.sbc` file, it's supposed to get written from the config I mentioned earlier but sometimes it doesn't.

**Comment by elwiregiven** [comment]
Working ! Thanks for your help.
