### ISSUE TITLE
Bug: Unable to interact with grid after dying and reconnecting before respawning.

### ISSUE THREAD

**Issue by inmotation** [TorchAPI/Torch#290]
- [X] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [X] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.18-54-g295bbd6 **SE Version:** 1.189.39

### Expected Behavior
Reconnect, respawn, be able to interact with grid.

### Observed Behavior
Reconnected, respawned, could open certain blocks, but could not sit down in any seats, use medbays, doors, or pilots chair. Problem is resolved if I cut/paste the grid back into the world.

### Steps to Reproduce
1. Die
2. Before respawn, disconnect
3. Reconnect
4. Attempt to interact with Grid

### Other Information
I've re-generated the world file several times. I've done it with and without mods. With and without plugins in torch. This has affected multiple copies of torch over the past month.

Taking the exact same worldfile and shoving it into vanilla SEDS does not allow me to reproduce the problem.

**Comment by Jimmacle** [comment]
It sounds like desync but it's strange that you can't reproduce it on vanilla. Send me the world file here (or over Discord if it's a live world) and I'll investigate.

**Comment by inmotation** [comment]
I actually managed to resolve the issue, and it is a strange one. Hardware specific. SEDS was just fine with that machine running at 5.5ghz. Torch was grumpy AF until I clocked it down to 5.2. Once I did that, the problem went away entirely. Didn't think to check that since no other programs or services were behaving abnormally.
