### ISSUE TITLE
Custom install...

### ISSUE THREAD

**Issue by DigitalNikki** [TorchAPI/Torch#291]
Please make it so we can have custom installs.
It should not be require to re-download SteamCMD/SE Dedicated Server, and use the existing SteamCMD/Dedicated Server.

Currently the only option is to re-download SteamCMD/SE Dedicated Server

**Comment by Jimmacle** [comment]
Torch manages DS updates itself so it needs the files to be in a specific structure and state. You can try installing Torch at the appropriate folder level but SteamCMD will likely try to redownload the server anyway. It's only like 2GB.

**Comment by DigitalNikki** [comment]
It's still a feature request. Control of updates, and install locations should not be taken away from the system administrator.

I can't allow torch on any of my systems until it has these features.

**Comment by Jimmacle** [comment]
Allowing the vanilla content location to change adds too many variables to the already tricky stuff we're doing to the assembly loader so we don't have plans to change it. You can choose where to install Torch itself, consider the whole thing one package (because it is).

**Comment by foogs** [comment]
Try hardlinks

**Comment by DigitalNikki** [comment]
Hardlinks do not solve anything, and the location of content doesn't need to be changed.

**Comment by DigitalNikki** [comment]
> 
> 
> Allowing the vanilla content location to change adds too many variables to the already tricky stuff we're doing to the assembly loader so we don't have plans to change it. You can choose where to install Torch itself, consider the whole thing one package (because it is).

Thanks for showing you're a poor developer, and this program is not safe to be used as released from here.

**Comment by Jimmacle** [comment]
If that's your attitude I don't want you in my community anyway.

**Comment by rexxar-tc** [comment]
Look, you cannot insult developers and expect to get your way. If you think it's so simple, then you can always submit a pull request.

As others have said, a hard link is the best workaround.

**Comment by hades200082** [comment]
Hi guys, 

I'm pretty new to SE servers but I'm a .net developer in my day job and have been developing in .net and other languages for over 20 years... so ignoring the insults thrown around above, here goes....

One thing I've found to be true of most systems, languages & frameworks... hard-coding file system paths is, almost always, a bad idea.

That's not to say that you can't use specific folder structures for your application to know where things are... but allowing more configuration around where those folder structures site on the file-system can help server admins have more control over their systems and can help to prevent having duplicated files scattered all over the place unnecessarily.

It should be a fairly simple matter to allow one instance of steamcmd/se-ds to run multiple dedicated servers by simply allowing the server admin to set two paths in the torch config (you can ask them to select these on first start and save them somewhere if you want, or simply have them as appsettings in Torch.Server.exe.config

- One path would be the path to the folder containing SteamCMD.
- The other would be the path to the folder that should contain the SE-DS.

Once they've been set you can store them in variables and use them wherever you need to access anything under either of those paths.

For both paths, a simple check for the relevant executable's existence in that location would tell you whether you need to download/install it or not.
