### ISSUE TITLE
Independent Console Always Opens again

### ISSUE THREAD

**Issue by Mr-Mors** [TorchAPI/Torch#292]
- [X] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [X] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.21.59

### Expected Behavior
With:
false

You should not have an independent console

### Observed Behavior
What actually happened?

### Steps to Reproduce
Update torch
Open torch.
No plugins loaded still has issue

### Other Information
No errors to report in log.

**Comment by rexxar-tc** [comment]
Can't reproduce. Delete your torch files and try again with a fresh copy from the website.

**Comment by JamieKG** [comment]
This happens for me on the patron branch only

**Comment by rexxar-tc** [comment]
Resolved in latest patron branch
