### ISSUE TITLE
Feature: Filter or Tag Faction chat from Torch chat window

### ISSUE THREAD

**Issue by JamieKG** [TorchAPI/Torch#295]
Would it be Possible to filter out or tag the faction chat in the Torch Chat/Players 

Thanks JamieKG

**Comment by N1Ran** [comment]
There seems to be an issue with Sandbox.Game.Gui which has the ChatChannel.  The Chat console is coded no to show faction chats, but still does.  This may be keen related.  The issue also extend to DiscordBridge plugin

**Comment by Jimmacle** [comment]
Implemeted tags 72ceeffdad78890912708c0193fd8ac80c3f9b51
