### ISSUE TITLE
Command/Permissions System

### ISSUE THREAD

**Issue by Jimmacle** [TorchAPI/Torch#3]
A centralized chat command system to simplify adding chat commands through plugins and to allow server admins to easily control which players can use certain commands through permission groups.

**Comment by Taki7o7** [comment]
love this :)

**Comment by Jimmacle** [comment]
Update: Commands system working as of 10836cbbb2f3c8d7ae48bc6b7e4e18318d31b824, still getting the permissions system integrated.

**Comment by Jimmacle** [comment]
Vanilla rank based permissions added in 650ab05d74854a52264fc37da614bb63a2b4475a, detailed permissions system still in the works.
