### ISSUE TITLE
admin commands hidden in chat

### ISSUE THREAD

**Issue by Darkonmaze** [TorchAPI/Torch#300]
Can you hide admin commands in chat

**Comment by N1Ran** [comment]
This is useful to track when commands were ran and if a crash was caused by command.  Also, this should only show up to the person running the command and the consoles.

**Comment by Darkonmaze** [comment]
nope it shows up for everyone ingame... even nonadmins

**Comment by N1Ran** [comment]
check your Torch version.  That has already been fixed

**Comment by Darkonmaze** [comment]
can i get a link to the download site please

**Comment by N1Ran** [comment]
https://torchapi.net/

**Comment by Darkonmaze** [comment]
ok thanks
