### ISSUE TITLE
[Suggestion] Add ability to scroll on settings panel

### ISSUE THREAD

**Issue by mbiddle** [TorchAPI/Torch#305]
- [ ] Add the ability to scroll on settings panel on the Configuration tab while the server is running.

**Torch Version:** 1.3.1.25-master **SE Version:** 1.189.44

### Expected Behavior
I expected to be able to view the settings while the server is running.

### Observed Behavior
I could not scroll up or down on the settings panel

### Steps to Reproduce
1. Start the server
2. Try to scroll down on the settings panel

### Other Information
Talked to Jimmacle about this in Discord #help.

**Comment by Jimmacle** [comment]
Duplicate of #281
