### ISSUE TITLE
Planets only visible when close

### ISSUE THREAD

**Issue by Sadragos** [TorchAPI/Torch#307]
- [?] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
I don't know if it's vanilla, but on a vanilla dedicated server the planets were visible as expected
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
Everyone on the Server does not see the planets unless they are really close
- [-] Is this a suggestion? 
no

**Torch Version:** 1.3.1.34 **SE Version:** 1.190.009

### Expected Behavior
See all Planets when in Space as colourful dots, that grow bigger when you come closer.

### Observed Behavior
Planets are only visible, when you are very close (near entering gravity well). Once a Planet was visitied it will stay this way for the length of the user session. Exploration is extremly difficult when you dont know where to go.

### Steps to Reproduce
1. Copy an existing world from DS, Star System Scenario and start up torch with it
2. JJoin the Server and go to space. Doesnt matter if in ship, in spacesuit or as spectator

### Other Information
-

**Comment by LordTylus** [comment]
I assume you have essentials installed

there is an option for client join tweaks, that causes planets to not be sent to the client until they really need them. change the settings to send planets regardless or disable it completely and it works all fine gain.

**Comment by Sadragos** [comment]
Yes, you were right. The problem was with essentials, however none of the join tweak-optionas changed the behaviour. Planets only show, when join tweaks are disabled completly. So no bug in torch. 

Thanks for the hint!
