### ISSUE TITLE
Request: dedicated_server.cfg should be applied on each server start

### ISSUE THREAD

**Issue by LordTylus** [TorchAPI/Torch#312]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [x] Is this a suggestion?

**Torch Version:**: v1.3.1.37-master **SE Version:** 1.190.001

### Expected Behavior
When I edit the dedicated_server.cfg file for example by enabling airtightness, changing mods, or other settings. I would expect these changes to take affect on next restart automatically.

Since we run 6 SE servers just changing a Setting on all of them is a very tedious job. Stopping all servers one by one, changing the setting and what not and start them back up. 

We have a small program we use to share setting across all the server which polls the information from a central database. But currently we cannot use that. It will show for example airtightness being enabled in the UI but unless we hit save to take these settings over to the sandbox.sbc file we wont have them in the game.

Needless to say changes performed ingame like for example banning a player or changing cleanup settings must not be overwritten. So its necessary to change the dedicated_server.cfg accordingly. Changes to the config must only change the values that are meant to be changed to not cause lost update problems on unrelated settings. 

### Observed Behavior
I set Airtightness from false to true and the servers didnt care. It kept being disabled. 

### Steps to Reproduce
See observed behavior

**Comment by JemiloII** [comment]
Just a heads up, even when you stop the server, makes updates, and hit config, when we restart, or manually close and restart, it does not persist the new settings.

**Comment by rexxar-tc** [comment]
Child of #270
