### ISSUE TITLE
Exception when launching

### ISSUE THREAD

**Issue by StarkITA** [TorchAPI/Torch#316]
- [x ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.37 **SE Version:** none

### Expected Behavior
What did you expect to happen?

To not crash torch on start

### Observed Behavior
What actually happened?

Torch crash and big error

### Steps to Reproduce
1. How did this issue get triggered?
I literally opened torch 
2. Write the steps here.
Download Torch
Open Torch

### Other Information
Error: https://pastebin.com/GyKn3wwE

I have downloaded torch, clean, opened it and had this pop up. Same with the existing installation.

**Comment by rexxar-tc** [comment]
Update Torch.

**Comment by StarkITA** [comment]
I literally just downloaded it from the website.

**Comment by StarkITA** [comment]
Whew. I refreshed and there is a new build!¯\_(ツ)_/¯

**Comment by StarkITA** [comment]
It still crashes :(

**Comment by MuFFkiNs** [comment]
Same here, fresh installation from latest V1.3.1.41Master, in the crash detail i get "System.IO.FileLoadException"

`

Log File [https://pastebin.com/gGFeD0Ln](url)

**Comment by Jimmacle** [comment]
Keen royally broke Torch by changing a bunch of assemblies, will update once we figure out how to deal with it.

**Comment by MuFFkiNs** [comment]
@Jimmacle , just tested a fresh v1.3.1.42Master and it failed to download StemCMD, should i be installing the SEDS manually??

Cheers, Love your work :)
