### ISSUE TITLE
June 6th SE update - Getting Could not load file or assembly 'System.Security.Principal.Windows, Version=4.1.1.0

### ISSUE THREAD

**Issue by attckdog** [TorchAPI/Torch#317]
**Torch Version:** 1.3.1.41-master  **SE Version:** up to date

### Expected Behavior
Server Start up
Testing on fresh install shows same error

### Observed Behavior
Was working fine. Space Engineers updated. 
Downloaded latest version 

### Steps to Reproduce
1. Download Latest version of Torch server 
2. unpack
3. Start Torch.Server.exe
4. Error is shown

### Other Information

17:50:38.1879 [INFO]   SteamCMD: Checking for DS updates.
17:50:39.1543 [INFO]   SteamCMD: Steam Console Client (c) Valve Corporation
17:50:39.2553 [INFO]   SteamCMD: -- type 'quit' to exit --
17:50:39.3562 [INFO]   SteamCMD: Loading Steam API...OK.
17:50:39.4572 [INFO]   SteamCMD: 
17:50:40.2481 [INFO]   SteamCMD: Connecting anonymously to Steam Public...Logged in OK
17:50:40.3484 [INFO]   SteamCMD: Waiting for user info...OK
17:50:41.0077 [INFO]   SteamCMD: Success! App '298740' already up to date.
17:50:42.1872 [INFO]   SteamCMD: force_install_dir ../
17:50:42.2881 [INFO]   Initializer: Loading config C:\Users\Admin\Downloads\torch-server\Torch.cfg
17:50:42.4211 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching begins...
17:50:42.5680 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 2/12.  (16%)
17:50:43.3376 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 3/12.  (25%)
17:50:43.3376 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 4/12.  (33%)
17:50:43.3376 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 5/12.  (41%)
17:50:43.3376 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 6/12.  (50%)
17:50:43.3446 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 8/12.  (66%)
17:50:43.3446 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 9/12.  (75%)
17:50:43.3446 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 10/12.  (83%)
17:50:43.3446 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 11/12.  (91%)
17:50:43.3446 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 12/12.  (100%)
17:50:43.3446 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching done
17:50:43.3736 [INFO]   Torch.Patches.PromotePatch: patching promote
17:50:43.4066 [INFO]   Initializer: Showing UI
17:50:43.4066 [INFO]   Torch: Initializing server
17:50:43.6835 [INFO]   Torch: RELEASE
17:50:43.6835 [INFO]   Torch: Torch Version: v1.3.1.41-master
17:50:43.6835 [INFO]   Torch: Game Version: 1.191.20
17:50:43.6835 [INFO]   Torch: Executing assembly: Torch.Server, Version=1.3.1.41, Culture=neutral, PublicKeyToken=null
17:50:43.6835 [INFO]   Torch: Executing directory: C:\Users\Admin\Downloads\torch-server\
17:50:43.6875 [INFO]   Torch.Managers.PluginManager: Checking for plugin updates...
17:50:43.6875 [INFO]   Torch.Managers.PluginManager: Updated 0 plugins.
17:50:43.6875 [INFO]   Torch.Managers.PluginManager: Loading plugins...
17:50:43.6875 [INFO]   Torch.Managers.PluginManager: Loaded 0 plugins.
17:50:43.7344 [FATAL]  Initializer: System.IO.FileLoadException: Could not load file or assembly 'System.Security.Principal.Windows, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Security.Principal.Windows, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Sandbox.MyInitializer.InvokeBeforeRun(UInt32 appId, String appName, String userDataPath, Boolean addDateToLog)
   at Torch.VRageGame.Create() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 164
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 117
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

System.IO.FileLoadException: Could not load file or assembly 'System.Security.Principal.Windows, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Security.Principal.Windows, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Sandbox.MyInitializer.InvokeBeforeRun(UInt32 appId, String appName, String userDataPath, Boolean addDateToLog)
   at Torch.VRageGame.Create() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 164
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 117
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by Jimmacle** [comment]
Duplicate, been working on this all afternoon and will update once it's fixed.

**Comment by attckdog** [comment]
@Jimmacle  - Awesome, Thanks!
