### ISSUE TITLE
[ERROR]  Config: Invalid path assigned to InstancePath! Please report this immediately!

### ISSUE THREAD

**Issue by Larry1123** [TorchAPI/Torch#323]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** v1.3.1.53-master **SE Version:** 1.191.105

### Expected Behavior
Server to start.

### Observed Behavior
Log file with `Please report this immediately!` in it.

### Steps to Reproduce
1. Created a server on VeryGames.net.
2. Updated to latest torch version (reinstalling the server includes the latest version as it is).
3. Server will not start.

### Other Information
torch log: https://hastebin.com/muvidudeba.log
torch.cfg: https://hastebin.com/dulazekaro.xml
This is with a fresh DS on the host.

**Comment by rexxar-tc** [comment]
Seems to be a false positive. I've pushed an update that should resolve it in your case. Feel free to reopen the ticket if the problem persists.
