### ISSUE TITLE
Move torch self-update into Program so we can always update

### ISSUE THREAD

**Issue by rexxar-tc** [TorchAPI/Torch#324]
Current implementation triggers update on Manager.Attach, which will fail to update if Keen severely breaks things again.

Move updating closer to program entry point to make updating faster and easier.

**Comment by Jimmacle** [comment]
Better yet, move all installation/update related code to a separate executable to avoid all the type loading problems we have.

**Comment by rexxar-tc** [comment]
sounds like a Torch 2 feature
