### ISSUE TITLE
Torch CTD and no restart

### ISSUE THREAD

**Issue by GarretSidzaka** [TorchAPI/Torch#325]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.31.56

### Expected Behavior
Not to crash

### Observed Behavior
Sytem crashed to desktop.  

### Steps to Reproduce
nothing reported

### Other Information
https://pastebin.com/TFu1c7f9

**Comment by Jimmacle** [comment]
It looks like a hang in vanilla inventory code. If it's happening consistently it may be an issue with your save, but it's unlikely to be an issue with Torch.
