### ISSUE TITLE
Feature request!

### ISSUE THREAD

**Issue by Bishbash777** [TorchAPI/Torch#326]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [x] Is this a suggestion?

Notice in the image below the title for Torch's main UI is very messy and clumped with unnecessary information, making it hard to navigate and identify different instances. 

My suggestion is that instead of the first mention of Torch in the form title, it be replaced with the server/instance name, making it easier to identify which windows is for which server.

![image](https://user-images.githubusercontent.com/50243964/60132797-26989a80-9794-11e9-8c14-052dd68eb43d.png)

**Comment by rexxar-tc** [comment]
This is already implemented. Use InstanceName in torch cfg.
