### ISSUE TITLE
[IPBanPlugin] Crash when using ban/unban commands

### ISSUE THREAD

**Issue by Kurtz31000** [TorchAPI/Torch#331]
- [x] Plugin without GitHub Page issue

**Torch Version:** v1.3.1.64-master **SE Version:** 1191108

### Expected Behavior
The ban or unban of the concerned players without any Crashes.

### Observed Behavior
When I used the !ban <playername> command, the server instantly crashed. This also happens with the !unban command.
Logs listed below.

### Other Information

LOGS : https://pastebin.com/bK7Mk4Pj

**Comment by Kurtz31000** [comment]
May I try a little up for this annoying bug ? We can't ban anyone since this issue exists...

With Love.

**Comment by Jimmacle** [comment]
Not an issue with Torch itself
