### ISSUE TITLE
Torch server failing to launch. Logs attached

### ISSUE THREAD

**Issue by Deathlock187** [TorchAPI/Torch#334]
I could use a little help all the info i have is listed. I have set up a few servers for other games but am still new to the process. if there is anything else i need to include please let me know and thank you in advanced for your time.

**Torch Version:** 1.3.1.65 **SE Version:** 1.191.108

### Expected Behavior
server to launch

### Observed Behavior
when i click start on the torch panel after finishing the config i get "Torch encountered a fatal error and needs to close. Please check the logs for details." below is the torch log

Wiki was followed to setup file path is C:\SEServer IP is correct and port is open.
no plugins used just a base install of what torch itself pulled down
The server is setup on  VM with i7 9x Nehalem class core 2.27 GHz, 16g ram, and SSD
server PC is currently able to host several other games without issue so idk if it could be it or not.

### Steps to Reproduce
launch torch.server
click start
profit????

### Other
03:47:46.5864 [INFO]   SteamCMD: Downloading SteamCMD.
03:47:47.0154 [INFO]   SteamCMD: SteamCMD downloaded successfully!
03:47:47.0154 [INFO]   SteamCMD: Checking for DS updates.
03:48:13.9324 [INFO]   SteamCMD: Steam Console Client (c) Valve Corporation
03:48:14.0334 [INFO]   SteamCMD: -- type 'quit' to exit --
03:48:14.1344 [INFO]   SteamCMD: Loading Steam API...OK.
03:48:14.2344 [INFO]   SteamCMD: 
03:48:35.7334 [INFO]   SteamCMD: Connecting anonymously to Steam Public...Logged in OK
03:48:40.3414 [INFO]   SteamCMD: Waiting for user info...OK
03:49:48.0824 [INFO]   SteamCMD:  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
03:49:48.1824 [INFO]   SteamCMD:  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
03:49:48.2824 [INFO]   SteamCMD:  Update state (0x1) running, progress: 0.00 (0 / 684608992)
03:49:48.4164 [INFO]   Initializer: Generating default config at C:\SEServer\Torch.cfg
03:49:52.1944 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching begins...
03:49:52.6044 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 2/12.  (16%)
03:49:55.6324 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 3/12.  (25%)
03:49:55.7154 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 4/12.  (33%)
03:49:55.7214 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 5/12.  (41%)
03:49:55.7214 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 6/12.  (50%)
03:49:55.7214 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 8/12.  (66%)
03:49:55.7214 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 9/12.  (75%)
03:49:55.7214 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 10/12.  (83%)
03:49:55.7214 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 11/12.  (91%)
03:49:55.7214 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 12/12.  (100%)
03:49:55.7214 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching done
03:49:55.8434 [INFO]   Torch.Patches.PromotePatch: patching promote
03:49:55.9064 [INFO]   Initializer: Showing UI
03:49:55.9064 [INFO]   Torch: Initializing server
03:49:56.6614 [INFO]   Torch: RELEASE
03:49:56.6614 [INFO]   Torch: Torch Version: v1.3.1.65-master
03:49:56.6614 [INFO]   Torch: Game Version: 1.191.108
03:49:56.6614 [INFO]   Torch: Executing assembly: Torch.Server, Version=1.3.1.65, Culture=neutral, PublicKeyToken=null
03:49:56.6614 [INFO]   Torch: Executing directory: C:\SEServer\
03:49:56.6724 [INFO]   Torch.Managers.PluginManager: Checking for plugin updates...
03:49:56.6724 [INFO]   Torch.Managers.PluginManager: Updated 0 plugins.
03:49:56.6724 [INFO]   Torch.Managers.PluginManager: Loading plugins...
03:49:56.7184 [INFO]   Torch.Managers.PluginManager: Loaded 0 plugins.
03:49:59.6184 [INFO]   Torch.VRageGame: Setting up serializers
03:50:01.6904 [INFO]   InstanceManager: Loading instance C:\SEServer\Instance
03:50:01.8144 [WARN]   InstanceManager: No worlds found in the current instance C:\SEServer\Instance.
03:50:01.8174 [INFO]   Torch: Initialized server 'Torch' at 'C:\SEServer\Instance'
03:50:02.5954 [INFO]   Torch.Managers.UpdateManager: Torch is up to date.
03:52:44.7606 [INFO]   Torch.Server.Managers.WorldViewModel: Preloading checkpoint C:\SEServer\Instance\Saves\Star System\Sandbox.sbc
03:55:46.6988 [INFO]   InstanceManager: Saved dedicated config.
03:55:46.7238 [INFO]   InstanceManager: Saved world config.
03:55:51.0108 [INFO]   InstanceManager: Saved dedicated config.
03:55:51.0388 [INFO]   InstanceManager: Saved world config.
03:55:51.0478 [INFO]   Torch: Starting server.
03:56:11.2738 [FATAL]  Initializer: System.Exception: Fatal error during dedicated server init see log for more information.
   at .ctor_0(Object , String[] )
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 235
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 119
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.Exception: Fatal error during dedicated server init see log for more information.
   at .ctor_0(Object , String[] )
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 235
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 119
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
03:56:11.3928 [INFO]   Initializer: Generating minidump at C:\SEServer\Instance\Minidump.dmp
03:56:11.3928 [ERROR]  Initializer: Keen broke the minidump, sorry.
03:56:32.6058 [INFO]   SteamCMD: Checking for DS updates.
03:56:34.5788 [INFO]   SteamCMD: Steam Console Client (c) Valve Corporation
03:56:34.6798 [INFO]   SteamCMD: -- type 'quit' to exit --
03:56:34.7808 [INFO]   SteamCMD: Loading Steam API...OK.
03:56:34.8818 [INFO]   SteamCMD: 
03:56:35.4208 [INFO]   SteamCMD: Connecting anonymously to Steam Public...Logged in OK
03:56:35.5208 [INFO]   SteamCMD: Waiting for user info...OK
03:56:36.7838 [INFO]   SteamCMD: Success! App '298740' already up to date.
03:56:36.9258 [INFO]   SteamCMD: force_install_dir ../
03:56:37.0268 [INFO]   Initializer: Loading config C:\SEServer\Torch.cfg
03:56:37.3618 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching begins...
03:56:37.7198 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 2/12.  (16%)
03:56:39.7178 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 3/12.  (25%)
03:56:39.7178 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 4/12.  (33%)
03:56:39.7178 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 5/12.  (41%)
03:56:39.7308 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 6/12.  (50%)
03:56:39.7308 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 8/12.  (66%)
03:56:39.7308 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 9/12.  (75%)
03:56:39.7308 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 10/12.  (83%)
03:56:39.7308 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 11/12.  (91%)
03:56:39.7308 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 12/12.  (100%)
03:56:39.7308 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching done
03:56:39.8028 [INFO]   Torch.Patches.PromotePatch: patching promote
03:56:39.8528 [INFO]   Initializer: Showing UI
03:56:39.8528 [INFO]   Torch: Initializing server
03:56:40.6488 [INFO]   Torch: RELEASE
03:56:40.6488 [INFO]   Torch: Torch Version: v1.3.1.65-master
03:56:40.6488 [INFO]   Torch: Game Version: 1.191.108
03:56:40.6488 [INFO]   Torch: Executing assembly: Torch.Server, Version=1.3.1.65, Culture=neutral, PublicKeyToken=null
03:56:40.6488 [INFO]   Torch: Executing directory: C:\SEServer\
03:56:40.6488 [INFO]   Torch.Managers.PluginManager: Checking for plugin updates...
03:56:40.6488 [INFO]   Torch.Managers.PluginManager: Updated 0 plugins.
03:56:40.6488 [INFO]   Torch.Managers.PluginManager: Loading plugins...
03:56:40.6808 [INFO]   Torch.Managers.PluginManager: Loaded 0 plugins.
03:56:43.5708 [INFO]   Torch.VRageGame: Setting up serializers
03:56:45.7668 [INFO]   InstanceManager: Loading instance C:\SEServer\Instance
03:56:45.8798 [INFO]   Torch.Server.Managers.WorldViewModel: Preloading checkpoint C:\SEServer\Instance\Saves\Star System\Sandbox.sbc
03:56:46.7478 [INFO]   Torch.Managers.UpdateManager: Torch is up to date.
03:56:47.0598 [INFO]   ModListControl: Instance loaded.
03:56:47.0848 [INFO]   Torch: Initialized server 'Torch' at 'C:\SEServer\Instance'
03:57:46.8328 [INFO]   InstanceManager: Saved dedicated config.
03:57:47.1788 [INFO]   InstanceManager: Saved world config.
03:57:47.9498 [INFO]   InstanceManager: Saved dedicated config.
03:57:47.9808 [INFO]   InstanceManager: Saved world config.
03:57:56.5838 [INFO]   InstanceManager: Saved dedicated config.
03:57:56.6128 [INFO]   InstanceManager: Saved world config.
03:57:57.0688 [INFO]   InstanceManager: Saved dedicated config.
03:57:57.0938 [INFO]   InstanceManager: Saved world config.
03:57:57.2628 [INFO]   InstanceManager: Saved dedicated config.
03:57:57.2818 [INFO]   InstanceManager: Saved world config.
03:57:57.6328 [INFO]   InstanceManager: Saved dedicated config.
03:57:57.6608 [INFO]   InstanceManager: Saved world config.
03:58:10.0548 [INFO]   InstanceManager: Saved dedicated config.
03:58:10.0768 [INFO]   InstanceManager: Saved world config.
03:58:10.1018 [INFO]   Torch: Starting server.
03:58:29.9768 [FATAL]  Initializer: System.Exception: Fatal error during dedicated server init see log for more information.
   at .ctor_0(Object , String[] )
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 235
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 119
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.Exception: Fatal error during dedicated server init see log for more information.
   at .ctor_0(Object , String[] )
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 235
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 119
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
03:58:29.9928 [INFO]   Initializer: Generating minidump at C:\SEServer\Instance\Minidump.dmp
03:58:29.9928 [ERROR]  Initializer: Keen broke the minidump, sorry.

**Comment by Jimmacle** [comment]
You'll need to upload the `Keen-###-##-##.log`, that's where the root error is in this case.

**Comment by Dradonis** [comment]
I have the same error, even after a full wipe and reinstall without even having a server created yet, also deleted the app data files and program data files

**Comment by N1Ran** [comment]
You'll need to upload the Keen-###-##-##.log, that's where the root error is in this case.

**Comment by Dradonis** [comment]
There is no Keen log file produced the app data folder is empty, and there is no other location it could be

**Comment by N1Ran** [comment]
That's not the same error.  You need to update your Torch
https://torchapi.net/download/Torch

**Comment by Dradonis** [comment]
Major facepalm, sorry not enough coffee today. Yeah needed updating, thought it would do that itself. 

Thanks

**Comment by ZxrroVal** [comment]
> Mayor facepalm, lo siento, no hay suficiente café hoy. Sí, necesitaba una actualización, pensé que lo haría solo.
> 
> Gracias

Era esa la solución?
