### ISSUE TITLE
Need a GUI field to edit PiratePCU

### ISSUE THREAD

**Issue by inmotation** [TorchAPI/Torch#338]
Need a GUI entry to modify the PiratePCU value in the Sandbox.sbc file

It defaults to PiratePCU>50000

every time, and the number being that low seems to break the NPC shops ability to spawn ships in some cases.

Can't edit it by hand, since Torch just auto-sets it back to 50,000

Semi-related, I was half asleep when I originally put this issue under the Essentials plugin.

Sorry about that.

**Comment by Jimmacle** [comment]
Added to cleanup branch, will be merged into main later https://github.com/TorchAPI/Torch/commit/45afd8d8744a3704985eea649b869bd440d40ba5

**Comment by serialtasted** [comment]
Was this added? I can't seem to find this field
