### ISSUE TITLE
[REQUEST] Add countdown/full exit to stop command

### ISSUE THREAD

**Issue by HeadWord** [TorchAPI/Torch#340]
- [ Yes ] Is this a suggestion?

**Torch Version:** [ All ]

### Expected Behavior
Restarts - I would LOVE for there to be an option either in GUI, CFG option or startup option that changes the way Restart works. I just want the option to have the restart just close the application and NOT reopen it.

I am running multiple instances of torch as consoles inside of windows session 0. When a restart is ran and the application closes (as normal) but then the server tries to restart it thinking it crashed. Then a moment later the app reloads its self causing there to be 2 instances running.

If I stop my services from caring about the app closing I then lose the ability to remotely monitor, manage, and restart them through my manager panel.

**Comment by rexxar-tc** [comment]
Use the !stop command instead of restart.

**Comment by HeadWord** [comment]
but does that still close the window when using -nogui ?

**Comment by HeadWord** [comment]
Also can it be used with stop 600 to have it act the same as a restart ?

**Comment by HeadWord** [comment]
I guess I should prefix it that way. I want restart to work exactly the same in all ways other than reopening the program after the window closes. Keeping restart in-game announces for warnings etc. letting players know its coming. Kind of like the autostart=false if there was restartmodeAorB=false 

I hope this makes more sense.

**Comment by N1Ran** [comment]
So, basically a countdown feature for the stop command?

**Comment by Jimmacle** [comment]
I think it would make more sense to not think of this as changes to restart, because that's confusing. It's a request to add a countdown/full exit to the existing stop command.

**Comment by HeadWord** [comment]
I would LOVE the stop command or A command to work exactly the same as restart except not reopen the program after it closes. Right now stop only stops the server it does not close it.

I don't mind scheduling announcements to let players know of a pending restart my self through essentials but still need the stop to exit the program.

**Comment by HeadWord** [comment]
bump :)
