### ISSUE TITLE
07:44:27.5356 [ERROR]  Initializer: Keen broke the minidump, sorry.

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [TorchAPI/Torch#341]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.x.xxx.xxx **SE Version:** 1.xxx.xxx

### Expected Behavior
What did you expect to happen?

### Observed Behavior
What actually happened?

### Steps to Reproduce
1. How did this issue get triggered?
2. Write the steps here.

### Other Information
Provide links to game logs or saves here if necessary.

**Comment by REVIEWGAMINGMAN** [comment]
v1.3.1.1.76

**Comment by REVIEWGAMINGMAN** [comment]
new Torch  download latest release for a space engineers

**Comment by N1Ran** [comment]
need full log

**Comment by Jimmacle** [comment]
Please open a new issue and fill out the template according to the instructions.
