### ISSUE TITLE
[REQUEST] Confirmation on GUI close

### ISSUE THREAD

**Issue by scytero** [TorchAPI/Torch#344]
As the title says, i'd like to request a confirmation prompt or other safety method, to prevent a sudden server shutdown by unintentional closing of the GUI window (via [X]). A simple Prompt asking 
```
            Are you sure?
[ Of course! ] [ No, thanks for warning! ]
```
would be enought.

Compare to the window shown, when just stopping the server.

**Comment by Jimmacle** [comment]
Staged on cleanup branch https://github.com/TorchAPI/Torch/commit/6ac9027e3cc5a1f72d26f49568752361afee1fa4
