### ISSUE TITLE
ERROR]  Initializer: Keen broke the minidump, sorry.

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [TorchAPI/Torch#348]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:**  1.3.1.85

### Expected Behavior
once I put my saving

### Observed Behavior
What actually happened?

### Steps to Reproduce
1. How did this issue get triggered? once I put my saving
2. Write the steps here. once I put my saving

### Other Information
Torch log https://pastebin.com/xscnkKLt 
keen log https://pastebin.com/NLtG6uhW

**Comment by Jimmacle** [comment]
You're missing dependencies, follow the getting started guide here: https://wiki.torchapi.net/index.php/Basic_Getting_Started_Guide
