### ISSUE TITLE
[Bug] Torch Plugin-Browser does not edit torch.cfg

### ISSUE THREAD

**Issue by LordTylus** [TorchAPI/Torch#350]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.86 **SE Version:** 1.192.102

### Expected Behavior
When using Plugin Browser in Torch UI and Download a plugin, I expect the plugin to appear in my plugin folder, and the plugins guid being added to the torch.cfg

### Observed Behavior
Plugin is downloaded
torch.cfg is not edited

### Steps to Reproduce
1. Use Plugin Browser
2. Select a few Plugins 
3. Notice some Plugins (like Player grace) dont trigger a feedback after clicking download
4. Projector filter however does. 
5. notice after restart (as instructed) Plugins being ignored due to missing entry in torch.cfg

### Other Information
23:20:43.2638 [WARN]   PluginManager: Plugin ProjectorFilter (F:\SE\Space Engineers\Server\torch-server\Plugins\ProjectorFilter.zip) exists in the plugin directory, but is not listed in torch.cfg. Skipping load!

**Comment by rexxar-tc** [comment]
Fixed
