### ISSUE TITLE
Server crashes frequently and while no one is on.

### ISSUE THREAD

**Issue by bodyboarder2528** [TorchAPI/Torch#356]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.93 **SE Version:** 1.193.21

### Expected Behavior
To work as it has been for months and nothing has been changed recently so this spontanious issue shouldn't of happened

### Observed Behavior
The server sim fluxuates alot even when nothing is happening and no one is online, it even crashes when no one is on. Also the voxel count persisten even when i do !voxels cleanup asteroids true

### Steps to Reproduce
unsure it just started about 2 days ago

### Other Information
Provide links to game logs or saves here if necessary.
[Torch-2019-11-06.log](https://github.com/TorchAPI/Torch/files/3812936/Torch-2019-11-06.log)
[Keen-2019-11-06.log](https://github.com/TorchAPI/Torch/files/3812937/Keen-2019-11-06.log)
https://i.imgur.com/NwJOexm.png
https://i.imgur.com/LZ0JM1Z.png
https://i.imgur.com/j9JyszP.png
https://i.imgur.com/5kPTiCG.png
https://i.imgur.com/gwH5PIh.png
https://i.imgur.com/Cu9aCHA.png
https://i.imgur.com/LCGR3sM.png
https://i.imgur.com/E3EHa28.png

**Comment by bodyboarder2528** [comment]
can join server 103.212.227.140:27016

**Comment by rexxar-tc** [comment]
For one, your concealment settings are probably wrong. It should not be updating every second.

Second, apart from the one UI crash, your issue is something in the world causing the main thread to freeze. Probably a mod or something.

The UI crash is known, but it's rare-ish and random, so we don't intend on doing anything about it right now, as the entire UI is going to be thrown away and redone soon.

**Comment by bodyboarder2528** [comment]
Vanilla server and concealment settings haven't been changed for a month and our server 1 has same concealment setting anf its fine and that's vanilla as well

**Comment by bodyboarder2528** [comment]
Is there anything you can recommend we can do to fix it

**Comment by bodyboarder2528** [comment]
rexxar regarding our concealment issue we just found out that our server 1 never updated torch version but server 2 did https://i.imgur.com/fwiAWNC.png And server 2 has the  which is the latest torch

**Comment by bodyboarder2528** [comment]
old and no longer valid
