### ISSUE TITLE
Torch logs location change

### ISSUE THREAD

**Issue by mawh1** [TorchAPI/Torch#357]
Change it so torch logs go into each instance folder, and only display that instances log data instead of the root install folder for all

**Comment by raegenhere** [comment]
Would welcome a change like that as well. Reason is, I am on a rented server running torch, and they only let me access the instance folder. Which is probably sensible from from their persepektive and I image other providers do it the same way. But it means I have to request the logs, in case I need them.

**Comment by roberestarkk** [comment]
Seconded, and for the same reasons as raegenhere

**Comment by Azuna1** [comment]
You can edit the NLog.config and NLog-user.config file to change logging behaviour (like different path)
