### ISSUE TITLE
Entity Manager displays incorrect ownership ids with Mod-Spawned Non-Space Pirate NPC ships.  

### ISSUE THREAD

**Issue by RoyAwesome** [TorchAPI/Torch#358]
- [X] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [X] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.95 **SE Version:** 1.xxx.xxx

### Expected Behavior
Entity Manager should show the proper entity ID for mod-added NPC ships belonging to non-space pirate factions

### Observed Behavior
Mod-Spawned, Non-Space Pirate NPC ships show up in the entity manager as owned by id:0, but they are not owned by nobody.  

Entity Manager showing ID:0 Grids
https://cdn.discordapp.com/attachments/262467504830414848/651589338152435733/unknown.png

Cleanup not showing the above grids:
https://cdn.discordapp.com/attachments/262467504830414848/651589252924309504/unknown.png

### Steps to Reproduce
1. Install the mods Modular Encounters Spawner and Exploration Enhanced (linked below)
2. Allow the mods to spawn a number of NPC grids (a player must be in game)
3. Observe the Entity Manager list in Torch.  See that the NPC spawned grids are owned by id:0, but tools like `!cleanup list ownedby nobody` do not see them           

### Other Information
Mods Used: 
 1. https://steamcommunity.com/sharedfiles/filedetails/?id=1521905890
 2. https://steamcommunity.com/sharedfiles/filedetails/?id=531659576

Save file with these ships available on request, although the modlist for that save is much larger.

**Comment by Jimmacle** [comment]
Solution is probably to fix https://github.com/TorchAPI/Torch/blob/42a66b04c58c13547b7851f0472400b7ab1f29c4/Torch/Utils/MiscExtensions.cs#L66 so it can look up the names of NPC identities if someone wants to get to it before I do

**Comment by Jimmacle** [comment]
Fixed 21fd997554969ad915026ba4b5aecc6ebee2ff06
