### ISSUE TITLE
Modlist gets reverted

### ISSUE THREAD

**Issue by KyuubiYoruAD** [TorchAPI/Torch#361]
**Torch Version:** 1.3.1.99 **SE Version:** 1.193.103

### Expected Behavior
Stop SE Server, change modlist and save config, start SE Server with changed modlist.
 
### Observed Behavior
After starting the SE Server the modlist gets reverted, it only works if i restart first torch.

### Steps to Reproduce
1. Have a runing SE server
2. Stop SE server
3. Change mods
4. Save mod changes
5. Start SE server
6. All mods are reverted

**Comment by Jimmacle** [comment]
Don't edit the configuration after stopping the server, it isn't currently supported.
