### ISSUE TITLE
 Error binding server endpoint: The requested address is not valid in its context?

### ISSUE THREAD

**Issue by TheBluKat** [TorchAPI/Torch#362]
- [x ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** v1.3.1.99-master **SE Version:** 1.193.103

### Expected Behavior
What did you expect to happen?

### Observed Behavior
18:41:24.6575 [DEBUG]  Keen:       MyCubeGridDefinitions - END
18:41:24.6575 [DEBUG]  Keen:       MyDefinitionManager - START
18:41:24.6735 [DEBUG]  Keen:       MyDefinitionManager - END
18:41:24.6735 [DEBUG]  Keen:    Preallocate - END
18:41:24.6735 [DEBUG]  Keen:    Bind IP : 203.59.54.9:27018
18:41:26.6572 [INFO]   Keen:    Error binding server endpoint: The requested address is not valid in its context?

### Steps to Reproduce
1. set ip address in config GUI
2. Save, Close Start.

### Other Information
Provide links to game logs or saves here if necessary.
[Keen-2020-01-13.log](https://github.com/TorchAPI/Torch/files/4053390/Keen-2020-01-13.log)
[Torch-2020-01-13.log](https://github.com/TorchAPI/Torch/files/4053391/Torch-2020-01-13.log)

**Comment by Jimmacle** [comment]
The IP you set is invalid, it should be the address of the network interface you want to bind or 0.0.0.0 to bind to all available interfaces.
