### ISSUE TITLE
Configuration option to disable DS update before starting the server

### ISSUE THREAD

**Issue by viktor-ferenczi** [TorchAPI/Torch#363]
**Torch Version:** 1.3.1.99 **SE Version:** 1.193.103

Whenever Torch starts the SE dedicated server it forces an update in `Initializer.RunSteamCmd`:

`log.Info("Checking for DS updates.");`

In the case of the system we built ( [https://spacewar.se](https://spacewar.se) ) we run new dedicated servers based on player needs and recycle unused lobbies periodically. It causes a lot of DS updates, which tend to fail or take too long due to Steam being slow at processing requests from time to time. We are not throttled or limited in any way, it is just due to temporary problems on Steam's side.

I suggest adding a configuration option to Torch.cfg to disable the DS update. It could be done by adding such an option and simply making the related code block conditional.

Updates would be done by periodically updating the DS image we clone before starting each server.

Default behavior would be the current one, e.g. updating each time before starting the DS.

**Comment by Jimmacle** [comment]
It does look like we're missing an option to specifically disable vanilla DS file updates. You can use the `-noupdate` command line argument for now to disable updating all components. The next major update of Torch will improve the update checking process and not require waiting for SteamCMD to complete each launch.

**Comment by viktor-ferenczi** [comment]
Thank you for the suggestion. My bad, actually. I passed `-NoUpdate` instead of `-noupdate`. I'm changing it now, hopefully it will help.

I would be happy to submit a PR with the new configuration option, but current master cannot be built. I ask for #help on Discord to get it built first.

**Comment by viktor-ferenczi** [comment]
Passing `-noupdate` helped, no DS update is attempted anymore. 

BTW, Torch does not report unknown command line parameters, it just silently ignores them. This is okay, but error prone.

**Comment by Jimmacle** [comment]
That should be fixed in the next big update as well since we'll be using a third party library to handle command line input.

**Comment by szczepix** [comment]
What is a `The next major update of Torch` or `next big update` @Jimmacle ?
Torch 2 is comming... ?
