### ISSUE TITLE
Sudden crash

### ISSUE THREAD

**Issue by Roshag** [TorchAPI/Torch#367]
**Torch Version:** 1.3.1.104 **SE Version:** 1.193.idk (latest)

### Expected Behavior
What did you expect to happen?

### Observed Behavior
Torch sometimes closes itself without any errors. Torch's log has no errors. Keen's log full of
`21:00:27.7214 [INFO]   Keen: Processing message: NotificationMessage
21:00:27.7214 [INFO]   Keen: Processing message: IncomingMessage
21:00:27.7214 [INFO]   Keen: TORCH MOD: Exception occurred in communication thread! System.Exception: Exception of type 'System.Exception' was thrown.
   at Torch.Mod.Messages.NotificationMessage.ProcessServer() in C:\jenkins\workspace\Torch_Torch_master\Torch.Mod\Messages\NotificationMessage.cs:line 36
   at Torch.Mod.ModCommunication.DoProcessing() in C:\jenkins\workspace\Torch_Torch_master\Torch.Mod\ModCommunication.cs:line 99`

### Steps to Reproduce
1. Random

**Comment by rexxar-tc** [comment]
It's something to do with your notifications. Check any !notify commands in your autocommands

**Comment by Roshag** [comment]
!notify is not used, no commands were used at the moment of crash

**Comment by Jimmacle** [comment]
Can you upload the full log file? Something running on your server tried to send a notification to clients that wasn't formatted correctly.

**Comment by Roshag** [comment]
[Torch-2020-03-14.log](https://github.com/TorchAPI/Torch/files/4333278/Torch-2020-03-14.log)
[Keen-2020-03-14.log](https://github.com/TorchAPI/Torch/files/4333279/Keen-2020-03-14.log)

**Comment by Roshag** [comment]
Something is wrong with one of plugins, seems to be NPC Faction Fixer - this excepion happens the same second, when plugin removes NPCs
