### ISSUE TITLE
[BUG: Torch 1.0.180.471, SE 1.181.400] Watchdog does not catch failure to load world.

### ISSUE THREAD

**Issue by Varaxian** [TorchAPI/Torch#37]
### Expected Behavior
command line or shortcut, -autostart to start the server

### Observed Behavior
Happened once, then no longer.

### Steps to Reproduce
Literally stopped at the same time as https://github.com/TorchAPI/Torch/issues/36

**Comment by Jimmacle** [comment]
Duplicate of #36
