### ISSUE TITLE
Possibly get unlisted mod info

### ISSUE THREAD

**Issue by thakyZ** [TorchAPI/Torch#371]
Right now if you add a unlisted mod to the server mod list, it will display nothing for it's name.
Possibly figure out how to fetch the information and get it, since its seemingly possible.

**Comment by kippandrew** [comment]
Also having this issue. It's pretty annoying.

**Comment by kippandrew** [comment]
I did a little testing on this. It seems the Steam WebAPI does not allow fetching data on unlisted workshop items by authenticated users.

**Comment by thakyZ** [comment]
Well, I do know it is not able to, but what I have done personally as a workaround with other apps that get workshop collections, is parse the webpage's HTML when it's unlisted.
