### ISSUE TITLE
Exception thrown at startup

### ISSUE THREAD

**Issue by ZorianNL** [TorchAPI/Torch#372]
- [X ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.108-master **SE Version:** 1.194.081

### Expected Behavior
The interface to be shown where I can configure and start the server

### Observed Behavior
After running the torch.server.exe it checks for an update, says there is none and then it crashes down with an exception thrown.

### Steps to Reproduce
1. Had to reboot server because of a rollback.
2. Shut down server
3. Start up server
4. It checks for an update (which ain't there)
5. It throws an exception
6. The window closes and nothing happens furthermore

### Other Information
The error is not showing up in any logs, at all.
Luckily I managed to snap a screenshot of the window before it closed (which is VERY fast):

![image](https://user-images.githubusercontent.com/59239345/77458744-fc493b80-6dfe-11ea-903e-938cc07edc11.png)

**Comment by N1Ran** [comment]
Keen hotfix is here.
You need to manually update Torch.  Follow the steps provided in the wiki: https://wiki.torchapi.net/index.php/Basic_Getting_Started_Guide
