### ISSUE TITLE
Greyed out names when using Discord Plugin

### ISSUE THREAD

**Issue by bodyboarder2528** [TorchAPI/Torch#373]
- [x ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.109 **SE Version:** 1.194.081

### Expected Behavior
What did you expect to happen? To see the name of the person who sent the message via discord

### Observed Behavior
What actually happened? The name is censored out

### Steps to Reproduce
1. How did this issue get triggered? latest update
2. Write the steps here. Add discord plugin and have it send the discord chats to game

### Other Information
Provide links to game logs or saves here if necessary.
This is what it looks like now and Bish said its not the discord plugin
https://media.discordapp.net/attachments/643809955282944000/692943145666609232/20200327144712_1.jpg?width=1202&height=676

**Comment by LordTylus** [comment]
Thank you for the report. 

It may be related to the DIscord plugin itself. However the Servername when Context.Respond or !say does say something is also not displayed. 

So I was planning to create an issue for that just now myself. Seems you were faster

**Comment by bodyboarder2528** [comment]
Yea bish told me its a torch thing so i did this.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rexxar-tc** [comment]
Fixed on branch chat-fix 224a41bb61f9d94c5142b3d0b5c31a2bc9a4ea64

**Comment by bodyboarder2528** [comment]
Wheb will that go to the main version

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
