### ISSUE TITLE
[BUG: Torch 1.0.180.471, SE 1.181.400] chat grayed out when using -autostart 

### ISSUE THREAD

**Issue by JamieKG** [TorchAPI/Torch#38]
Torch 1.0.180.471, SE 1.181.400

### Expected Behavior
When starting Torch with -autostart I would expect the chat tab to function and the stop button to not be grayed out

### Observed Behavior
Chat/Players tab is all grayed out and unusable and the stop button it grayed out as if the server is not running altho its is

### Steps to Reproduce
create a shortcut to Torch.Server.exe and add the argument of -autostart then run the shortcut

### Other Information
![Torch Chat/Players Tab](http://i.imgur.com/FPizQyO.png)

**Comment by Jimmacle** [comment]
Fixed 79fe6a08ab04f2e612eab4bad65aaf815c5ff4fc
