### ISSUE TITLE
Exception on starting

### ISSUE THREAD

**Issue by eduelias** [TorchAPI/Torch#384]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.x.xxx.xxx **SE Version:** 1.xxx.xxx

### Expected Behavior
Server to start

### Observed Behavior
What actually happened?
![image](https://user-images.githubusercontent.com/12836540/80124880-325e1480-8591-11ea-9eed-73066edfe9fd.png)

### Steps to Reproduce
1. After a server crash it came back like this, logs are all empty

### Other Information
Removed the server folder, downloaded again, restarted the machine and, after run, happened again.
Reinstalled the VCRedists and .Net Framework without success.

**Comment by N1Ran** [comment]
Manually delete VRage.Platform.Windows.dll from the Torch root and update to v1.3.1.118-master to get running again after the SE update today: https://build.torchapi.net/job/Torch/job/Torch/job/master/lastSuccessfulBuild/artifact/bin/torch-server.zip
