### ISSUE TITLE
World load error after restart. No backups work.

### ISSUE THREAD

**Issue by BobDaRoss** [TorchAPI/Torch#387]
- [ No] Is this a suggestion?

**Torch Version:** 1.3.1.120 **SE Version:** 1.194.207

### Observed Behavior
We have been trying to load a world with no plugins now for each of our backup saves and it keeps throwing a loading world error. 

### Steps to Reproduce
1. The issue occurred after a server restart
2. It only happens on one of our worlds/Servers. I've tried going back a day and it's still throwing the error.

### Other Information
[Torch-2020-04-26.log](https://github.com/TorchAPI/Torch/files/4534866/Torch-2020-04-26.log)

World:
https://www.mediafire.com/file/4c7ucj1ihi33qjl/2020-04-25_220746.rar/file

**Comment by Jimmacle** [comment]
The Keen log file should have a more specific error about why the world failed to load. Based on the one in the log you provided it's likely an issue with duplicate entity IDs.

**Comment by BobDaRoss** [comment]
I see. 
[KeenLog.txt](https://github.com/TorchAPI/Torch/files/4536141/KeenLog.txt)

Here is the keen log. So Is there a way fix this entity then?

**Comment by Jimmacle** [comment]
That actually looks like the game failed to load a model or something related to the large gatling turret.

**Comment by BobDaRoss** [comment]
Interesting. So this could be related to a mod.

**Comment by BobDaRoss** [comment]
Yeah, I'm at a loss on how to fix this. This is our main server world. I wish it would tell us what entity then I could delete it.
SEToolbox gives the same error as well as any server/singleplayer world
