### ISSUE TITLE
Torch not always starting SE instance after a !restart or crash recovery

### ISSUE THREAD

**Issue by kontu** [TorchAPI/Torch#388]
- [x ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.120-Master **SE Version:** 1.194.211

### Expected Behavior
What did you expect to happen?
SE instance to stop (or crash), torch to close, torch to re-open, and torch to start the SE instance again

### Observed Behavior
What actually happened?
SE instance stops (or crashes), torch closes, torch re-opens, and torch does NOT start the SE instance again. Torch is open waiting user input clicking "Start"

### Steps to Reproduce
1. Randomly occurs some of the time on any of our 9 torch instances after a essentials autocommand  !restart
1b. Randomly occurs some of the time on any of our 9 torch instances after a instance crash (  <RestartOnCrash>true</RestartOnCrash> is set on all instances)

### Other Information
Logs from two separate instances

 Server !restart at 1200 ST; just sat there waiting to have "Start" pressed
[no_start.zip](https://github.com/TorchAPI/Torch/files/4651423/no_start.zip)

 Different torch instance; server crashed at 1656; torch restarted but never "started" server; start was pressed manually at 1830
[nostart_2.zip](https://github.com/TorchAPI/Torch/files/4651425/nostart_2.zip)

**Comment by SinisterSole** [comment]
If "Torch is open waiting user input clicking "Start"" happens on all instances, you need to set autostart in Torch.cfg or at least check that it is set to true.

**Comment by kontu** [comment]
While you are correct that setting Autostart to true works as a bandaid workaround for this issue; that is not related to this issue report.

Out of 54 !restart commands a day, we would see it get stuck waiting for us to press start 1/75 restarts (so once every day and a half) roughly. Never reliably the same instance.
