### ISSUE TITLE
Users do not have permission to use /help

### ISSUE THREAD

**Issue by zenduin** [TorchAPI/Torch#39]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)

**Torch Version:** 1.0.180.471**SE Version:** 1.181.401

### Expected Behavior
User gets list of commands they have permission to use.

### Observed Behavior
"*User* tried to use command help without permission"

### Steps to Reproduce
User without admin privilege types /help

**Comment by Jimmacle** [comment]
Fixed for the next update.

**Comment by Jimmacle** [comment]
Fixed 79fe6a08ab04f2e612eab4bad65aaf815c5ff4fc
