### ISSUE TITLE
Torch Server suddenly crashing at start

### ISSUE THREAD

**Issue by PrimeLetter** [TorchAPI/Torch#392]
Version: v1.3.1.120-master
Game Version: 1.195.21

### Expected Behavior
Start Server Normally

### Observed Behavior
Torch does not start the server successfully and quickly closes itself

### Steps to Reproduce
By starting the server normally via desktop shortcut

12:18:02.6678 [INFO]   SteamCMD: Checking for DS updates.
12:18:03.6585 [INFO]   SteamCMD: Steam Console Client (c) Valve Corporation
12:18:03.7596 [INFO]   SteamCMD: -- type 'quit' to exit --
12:18:03.8607 [INFO]   SteamCMD: Loading Steam API...OK.
12:18:03.9618 [INFO]   SteamCMD: 
12:18:04.6212 [INFO]   SteamCMD: Connecting anonymously to Steam Public...Logged in OK
12:18:04.7223 [INFO]   SteamCMD: Waiting for user info...OK
12:18:05.7401 [INFO]   SteamCMD: Success! App '298740' already up to date.
12:18:06.6868 [INFO]   SteamCMD: force_install_dir ../
12:18:06.7878 [INFO]   Initializer: Loading config C:\TorchSpaceEngineers\torch-server\Torch.cfg
12:18:07.2882 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching begins...
12:18:07.4063 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 2/12.  (16%)
12:18:07.4113 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 3/12.  (25%)
12:18:07.4113 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 4/12.  (33%)
12:18:07.4113 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 5/12.  (41%)
12:18:07.4113 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 6/12.  (50%)
12:18:07.4113 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 8/12.  (66%)
12:18:07.4113 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 9/12.  (75%)
12:18:07.4113 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 10/12.  (83%)
12:18:07.4113 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 11/12.  (91%)
12:18:07.4113 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 12/12.  (100%)
12:18:07.4113 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching done
12:18:07.4493 [INFO]   Torch.Patches.PromotePatch: patching promote
12:18:07.4783 [INFO]   Torch: Initializing server
12:18:08.5801 [INFO]   Torch: RELEASE
12:18:08.5801 [INFO]   Torch: Torch Version: v1.3.1.120-master
12:18:08.5801 [INFO]   Torch: Game Version: 1.195.21
12:18:08.5801 [INFO]   Torch: Executing assembly: Torch.Server, Version=1.3.1.120, Culture=neutral, PublicKeyToken=null
12:18:08.5801 [INFO]   Torch: Executing directory: C:\TorchSpaceEngineers\torch-server\
12:18:08.5881 [INFO]   Torch.Managers.PluginManager: Loading plugins...
12:18:08.6132 [INFO]   Torch.Managers.PluginManager: Checking for plugin updates...
12:18:08.6132 [INFO]   Torch.Managers.PluginManager: Updated 0 plugins.
12:18:08.6132 [INFO]   Torch.Managers.PluginManager: Loaded 0 plugins.
12:18:08.6132 [FATAL]  Initializer: System.MissingMethodException: Method not found: 'Void Sandbox.MyInitializer.InvokeBeforeRun(UInt32, System.String, System.String, Boolean, Int32)'.
   at Torch.VRageGame.Create()
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 117
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.MissingMethodException: Method not found: 'Void Sandbox.MyInitializer.InvokeBeforeRun(UInt32, System.String, System.String, Boolean, Int32)'.
   at Torch.VRageGame.Create()
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 117
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Jimmacle** [comment]
Your Torch is a couple versions behind and doesn't support the latest SE update. If it's not updating automatically, you can download the latest from https://torchapi.net/download and unzip the contents over your current installation.

**Comment by PrimeLetter** [comment]
Thank you for the quick response. I thought that I did download the latest version and copy it over the old version but I guess I messed something up. I'll try again.
