### ISSUE TITLE
14:25:03.1161 [FATAL]  Initializer: Sandbox.Game.Screens.MyLoadingException: An error occurred while adding one or more objects.

### ISSUE THREAD

**Issue by thebeast5268** [TorchAPI/Torch#395]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.195.23 **SE Version:** most recent as of 07/10/2020

### Expected Behavior
What did you expect to happen?

Expected DS to finalize and have game ready

### Observed Behavior
What actually happened?

Received Error and torch had to close

### Steps to Reproduce
1. How did this issue get triggered?

Opened torch and started server with existing world

2. Write the steps here.

Open torch and start server with existing world, including mods.

### Other Information
Provide links to game logs or saves here if necessary.

Entire torch DS log 
https://pastebin.com/Zb8MTjUY

**Comment by Jimmacle** [comment]
This is most likely due to a corrupt save or a problem with modded blocks.

**Comment by thebeast5268** [comment]
> This is most likely due to a corrupt save or a problem with modded blocks.

It's neither, as the save works with the vanilla host and removing all mods causes the same crash.
