### ISSUE TITLE
Torch crashing at Startup

### ISSUE THREAD

**Issue by Kadriel2ndCav** [TorchAPI/Torch#397]
- [X ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version: v1.3.1.123-master **SE Version:** Game Version: 1.196.11

### Expected Behavior
What did you expect to happen?
Torch opening normally

### Observed Behavior
Torch opened, updated SE, loaded plugins, then crashed

### Steps to Reproduce
1. How did this issue get triggered?
After updating SE to the latest version today, the issue occurred
2. Write the steps here.
Open Torch
Let it update SE, then load the plugins, then it crashes after it says plugins are loaded

### Other Information
Provide links to game logs or saves here if necessary.
21:14:21.0262 [INFO]   SteamCMD: Checking for DS updates.
21:14:21.9777 [INFO]   SteamCMD: Steam Console Client (c) Valve Corporation
21:14:22.0884 [INFO]   SteamCMD: -- type 'quit' to exit --
21:14:22.2003 [INFO]   SteamCMD: Loading Steam API...OK.
21:14:22.3091 [INFO]   SteamCMD: 
21:14:23.0101 [INFO]   SteamCMD: Connecting anonymously to Steam Public...Logged in OK
21:14:23.1203 [INFO]   SteamCMD: Waiting for user info...OK
21:14:23.8681 [INFO]   SteamCMD: Success! App '298740' already up to date.
21:14:24.1064 [INFO]   SteamCMD: force_install_dir ../
21:14:24.2102 [INFO]   Initializer: Loading config E:\Torch Server\Torch.cfg
21:14:24.5069 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching begins...
21:14:24.5770 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 2/12.  (16%)
21:14:24.5770 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 3/12.  (25%)
21:14:24.5770 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 4/12.  (33%)
21:14:24.5770 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 5/12.  (41%)
21:14:24.5850 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 6/12.  (50%)
21:14:24.5850 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 8/12.  (66%)
21:14:24.5850 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 9/12.  (75%)
21:14:24.5850 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 10/12.  (83%)
21:14:24.5850 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 11/12.  (91%)
21:14:24.5850 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 12/12.  (100%)
21:14:24.5850 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching done
21:14:24.6099 [INFO]   Torch.Patches.PromotePatch: patching promote
21:14:24.6249 [INFO]   Torch: Initializing server
21:14:25.1854 [INFO]   Torch: RELEASE
21:14:25.1854 [INFO]   Torch: Torch Version: v1.3.1.123-master
21:14:25.1854 [INFO]   Torch: Game Version: 1.196.11
21:14:25.1854 [INFO]   Torch: Executing assembly: Torch.Server, Version=1.3.1.123, Culture=neutral, PublicKeyToken=null
21:14:25.1854 [INFO]   Torch: Executing directory: E:\Torch Server\
21:14:25.1854 [INFO]   Torch.Managers.PluginManager: Loading plugins...
21:14:25.2173 [INFO]   Torch.Managers.PluginManager: Checking for plugin updates...
21:14:26.3805 [INFO]   Torch.Managers.PluginManager: Updated 0 plugins.
21:14:26.4503 [INFO]   Torch.Managers.PluginManager: Loading plugin at ALE_RestartWatchdog.RestartPlugin
21:14:26.4503 [INFO]   Torch.Managers.PluginManager: Loading plugin 'ALE Restart Watchdog' (v1.0.2.1)
21:14:26.4852 [INFO]   Torch.Managers.PluginManager: Loading plugin at Concealment.ConcealmentPlugin
21:14:26.4852 [INFO]   Torch.Managers.PluginManager: Loading plugin 'Concealment' (v1.4.1.21-21-g96540b3)
21:14:26.5470 [INFO]   Torch.Managers.PluginManager: Loading plugin at Essentials.EssentialsPlugin
21:14:26.5470 [INFO]   Torch.Managers.PluginManager: Loading plugin 'Essentials' (v1.7.1.62-132-g2cd7b68)
21:14:26.5620 [INFO]   Torch.Managers.PluginManager: Loading plugin at PerformanceTweaker.TweakerPlugin
21:14:26.5620 [INFO]   Torch.Managers.PluginManager: Loading plugin 'PerformanceTweaker' (1.0.5)
21:14:26.5840 [INFO]   Essentials: Attempting to load config from E:\Torch Server\Instance\Essentials.cfg
21:14:26.6079 [INFO]   Torch.Managers.PluginManager: Loaded 4 plugins.
21:14:26.6079 [FATAL]  Initializer: System.MissingMethodException: Method not found: 'Void VRageRender.MyNullRender..ctor()'.
   at Torch.VRageGame.Create()
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 117
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.MissingMethodException: Method not found: 'Void VRageRender.MyNullRender..ctor()'.
   at Torch.VRageGame.Create()
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 117
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Kadriel2ndCav** [comment]
**Original Torch Server/Instance**
Removed all 4 plugins and loaded Torch
Torch crashes at startup with the error listed in the original ticket post

**New Torch Server/Instance**
Downloaded Torch from scratch
Downloaded SteamCMD from scratch
Download SE from scratch
Torch loads successfully
Copied Instance from original server over
Torch loads successfully
Installed plugins (listed above), one at a time and loaded Torch
Torch loads successfully, on all 4
Started SE server after each plugin add
Server loads successfully on each plugin until Performance Tweaker
After installing PerformanceTweaker' (1.0.5), SE crashes
Removed PerformanceTweaker' (1.0.5), SE server loads
With PerformanceTweaker removed, everything is back to normal except for the new folder location

**Comment by Phoenix-Oren** [comment]
Same problem for me as of today on a New install and Uninstall/Reinstall.
With VS C++ Updated to 2017 and Framework.Net from 2.0 to 4.8 full installed and system rebooted. Windows 10,

**Reproduce:** attempted roughly 12 times in total to start with No plugins, and 3 or 4 with Essentials.

Run TorchServer.exe runs SteamCMD updater (normal) then opens the GUI, then fills the GUI with Red Errors and GUI auto closes.

_Repeats the Error of:_ [FATAL]  Initializer: System.MissingMethodException: Method not found: 'Void VRageRender.MyNullRender..ctor()'.
   at Torch.VRageGame.Create()
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 117

[Torch-2020-08-10 [Startup Crash Report].log](https://github.com/TorchAPI/Torch/files/5052549/Torch-2020-08-10.Startup.Crash.Report.log)

**Comment by Blacky244** [comment]
I have a solution for this problem, namely installed microsoft visual c++ 2005-2019 then the server can be started again without red text my server has started with this solution
