### ISSUE TITLE
Mods won't get downloaded after adding them through Torch GUI

### ISSUE THREAD

**Issue by chris007de** [TorchAPI/Torch#406]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.129-master **SE Version:** 1.196.016

### Expected Behavior
- Start Torch GUI
- Go to `Mods` tab
- Enter Mod ID (e.g. 914369510), Click Add
- Save Config
- Start Server
- Server shall download mod and have that mod enabled, but server browser shows that this server has no mods

### Observed Behavior
- Server starts, but without mod
- Keen Log says

> 12:18:32.0627 [INFO]   Keen:    Downloading world mods - START
> 12:18:32.0627 [INFO]   Keen:    Downloading world mods - END

 Although it should probably show some progress between these lines
- `Instance/Mods` folder is empty
- Sandbox_config.sbc looks proper

```
<Mods>
    <ModItem FriendlyName="Corruption PvE Combat">
      <Name>914369510.sbm</Name>
      <PublishedFileId>914369510</PublishedFileId>
    </ModItem>
  </Mods>
```

### Steps to Reproduce

see "Expected Behavior"

Any suggestions? Did I miss something?
Thanks a lot!

**Comment by steviee** [comment]
I have the same issue.

**Comment by pdglobal** [comment]
I have the same issue. Torch 1.3.1.141

**Comment by Necavi** [comment]
I was having this exact same issue until I realized that for some reason Torch was saving mods to the instance folder's sandbox_config.sbc but was LOADING from one of my Backup plugin's folders. 

I would recommend checking your LastSession.sbl file to ensure that you are loading from the correct save file.

**Comment by MeniMeniMeni** [comment]
I'm having this issue intermittently on Torch Version: v1.3.1.153-master. Torch fails to update the mod list in Sandbox_config.sbc when saving via the Mods GUI page. Sometimes it works, sometimes not.

It seems to happen when you try to edit the mod list after stopping a server. Stopping the server, closing and relaunching torch, then re-editing the mods, then saving config seems to work.
