### ISSUE TITLE
Torch killed the whole server with update today

### ISSUE THREAD

**Issue by sysworx** [TorchAPI/Torch#414]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** v1.3.1.131-master **SE Version:** 1.197.63

### Expected Behavior
Server should start like everyday

### Observed Behavior
Server destroyed himself on a update try and messed up the server folder

`20:37:17.2124 [INFO]   SteamCMD: Checking for DS updates.
20:37:21.3191 [INFO]   SteamCMD: Steam Console Client (c) Valve Corporation
20:37:21.4345 [INFO]   SteamCMD: -- type 'quit' to exit --
20:37:21.5445 [INFO]   SteamCMD: Loading Steam API...OK.
20:37:21.6539 [INFO]   SteamCMD: 
20:37:22.7823 [INFO]   SteamCMD: Connecting anonymously to Steam Public...Logged in OK
20:37:22.8925 [INFO]   SteamCMD: Waiting for user info...OK
20:38:25.7370 [INFO]   SteamCMD:  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
20:38:25.8471 [INFO]   SteamCMD:  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
20:38:25.9678 [INFO]   Initializer: Loading config C:\Servers\Torch\Torch.cfg
20:38:31.0960 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching begins...
20:38:31.1960 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 2/12.  (16%)
20:38:31.1960 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 3/12.  (25%)
20:38:31.2021 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 4/12.  (33%)
20:38:31.2021 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 5/12.  (41%)
20:38:31.2021 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 6/12.  (50%)
20:38:31.2021 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 8/12.  (66%)
20:38:31.2021 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 9/12.  (75%)
20:38:31.2021 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 10/12.  (83%)
20:38:31.2021 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 11/12.  (91%)
20:38:31.2021 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 12/12.  (100%)
20:38:31.2021 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching done
20:38:31.2410 [INFO]   Torch.Patches.PromotePatch: patching promote
20:38:31.2660 [INFO]   Torch: Initializing server
20:38:32.2200 [INFO]   Torch: RELEASE
20:38:32.2200 [INFO]   Torch: Torch Version: v1.3.1.131-master
20:38:32.2200 [INFO]   Torch: Game Version: 1.197.63
20:38:32.2200 [INFO]   Torch: Executing assembly: Torch.Server, Version=1.3.1.131, Culture=neutral, PublicKeyToken=null
20:38:32.2200 [INFO]   Torch: Executing directory: C:\Servers\Torch\
20:38:32.2200 [INFO]   Torch.Managers.PluginManager: Loading plugins...
20:38:32.2200 [INFO]   Torch.Managers.PluginManager: Checking for plugin updates...
20:38:32.2200 [INFO]   Torch.Managers.PluginManager: Updated 0 plugins.
20:38:32.2370 [INFO]   Torch.Managers.PluginManager: Loaded 0 plugins.
20:38:32.3881 [WARN]   Torch.VRageGame: Steam service is not running! Please reinstall dedicated server.
20:38:32.4871 [INFO]   InstanceManager: Loading instance D:\Tools\Torch\Instance
20:38:32.8514 [ERROR]  InstanceManager: Failed to load world at path: D:\Tools\Torch\Instance\Saves\Gamerz mining Red Planet LOS
20:38:32.8774 [ERROR]  InstanceManager: Failed to load world at path: D:\Tools\Torch\Instance\Saves\World
20:38:32.8774 [WARN]   InstanceManager: No worlds found in the current instance D:\Tools\Torch\Instance.
20:38:32.8774 [INFO]   Torch: Initialized server 'Torch' at 'D:\Tools\Torch\Instance'
20:38:33.2846 [INFO]   Torch.Managers.UpdateManager: Torch is up to date.
`
![image](https://user-images.githubusercontent.com/5045879/100274898-79fdb200-2f5f-11eb-87e0-31ee27e06cb6.png)

### Steps to Reproduce
1. Start the server

**Comment by rcdailey** [comment]
Mine fails too but for a different reason:

```
13:58:32.0430 [INFO]   Keen:    Exception while loading world: Object reference not set to an instance of an object.
13:58:32.0430 [INFO]   Keen: Plugin Init: Torch.Server.TorchServer
13:58:32.0430 [INFO]   Keen: Exiting..
13:58:32.0580 [WARN]   TorchSessionManager: Session unloading event occurred when we don't have a session.
13:58:32.0951 [INFO]   Keen: Autosave in unload
13:58:32.6602 [ERROR]  Keen: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.World.MySession.GetCheckpoint(String saveName, Boolean isClientRequest)
   at Sandbox.Game.World.MySession.Save(MySessionSnapshot& snapshot, String customSaveName)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.World.MySession.GetCheckpoint(String saveName, Boolean isClientRequest)
   at Sandbox.Game.World.MySession.Save(MySessionSnapshot& snapshot, String customSaveName)
13:58:32.8782 [INFO]   Keen: Logging off Steam...
13:58:32.8782 [INFO]   Keen: Shutting down server...
13:58:34.3231 [INFO]   Keen: Done
13:58:34.3750 [WARN]   TorchSessionManager: Session unloading event occurred when we don't have a session.
```

**Comment by DoktorKrove** [comment]
> Mine fails too but for a different reason:
> 
> ```
> 13:58:32.0430 [INFO]   Keen:    Exception while loading world: Object reference not set to an instance of an object.
> 13:58:32.0430 [INFO]   Keen: Plugin Init: Torch.Server.TorchServer
> 13:58:32.0430 [INFO]   Keen: Exiting..
> 13:58:32.0580 [WARN]   TorchSessionManager: Session unloading event occurred when we don't have a session.
> 13:58:32.0951 [INFO]   Keen: Autosave in unload
> 13:58:32.6602 [ERROR]  Keen: System.NullReferenceException: Object reference not set to an instance of an object.
>    at Sandbox.Game.World.MySession.GetCheckpoint(String saveName, Boolean isClientRequest)
>    at Sandbox.Game.World.MySession.Save(MySessionSnapshot& snapshot, String customSaveName)
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Sandbox.Game.World.MySession.GetCheckpoint(String saveName, Boolean isClientRequest)
>    at Sandbox.Game.World.MySession.Save(MySessionSnapshot& snapshot, String customSaveName)
> 13:58:32.8782 [INFO]   Keen: Logging off Steam...
> 13:58:32.8782 [INFO]   Keen: Shutting down server...
> 13:58:34.3231 [INFO]   Keen: Done
> 13:58:34.3750 [WARN]   TorchSessionManager: Session unloading event occurred when we don't have a session.
> ```

I am getting the exact same error

**Comment by sysworx** [comment]
First error was this and now its broken.

```
20:24:54.0091 [INFO]   SteamCMD: Connecting anonymously to Steam Public...Logged in OK
20:24:54.1191 [INFO]   SteamCMD: Waiting for user info...OK
20:25:48.3584 [INFO]   SteamCMD:  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
20:25:48.4676 [INFO]   SteamCMD:  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
20:25:48.5768 [INFO]   SteamCMD:  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
20:25:48.6991 [INFO]   Initializer: Loading config C:\Servers\Torch SPE\Torch.cfg
20:25:53.6549 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching begins...
20:25:53.7469 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 2/12.  (16%)
20:25:53.7500 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 3/12.  (25%)
20:25:53.7500 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 4/12.  (33%)
20:25:53.7500 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 5/12.  (41%)
20:25:53.7500 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 6/12.  (50%)
20:25:53.7500 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 8/12.  (66%)
20:25:53.7500 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 9/12.  (75%)
20:25:53.7500 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 10/12.  (83%)
20:25:53.7500 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 11/12.  (91%)
20:25:53.7500 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 12/12.  (100%)
20:25:53.7500 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching done
20:25:53.7900 [INFO]   Torch.Patches.PromotePatch: patching promote
20:25:53.8119 [INFO]   Torch: Initializing server
20:25:54.6709 [INFO]   Torch: RELEASE
20:25:54.6709 [INFO]   Torch: Torch Version: v1.3.1.131-master
20:25:54.6709 [INFO]   Torch: Game Version: 1.197.63
20:25:54.6709 [INFO]   Torch: Executing assembly: Torch.Server, Version=1.3.1.131, Culture=neutral, PublicKeyToken=null
20:25:54.6709 [INFO]   Torch: Executing directory: C:\Servers\Torch SPE\
20:25:54.6709 [INFO]   Torch.Managers.PluginManager: Loading plugins...
20:25:54.7209 [INFO]   Torch.Managers.PluginManager: Checking for plugin updates...
20:26:04.8611 [INFO]   Torch.Managers.PluginManager: Updated 0 plugins.
20:26:04.9781 [INFO]   Torch.Managers.PluginManager: Loading plugin at ALE_GridManager.GridManagerPlugin
20:26:04.9781 [INFO]   Torch.Managers.PluginManager: Loading plugin 'ALE PCU Transferrer' (v1.1.10.1)
20:26:05.0141 [INFO]   Torch.Managers.PluginManager: Loading plugin at ALE_RestartWatchdog.RestartPlugin
20:26:05.0141 [INFO]   Torch.Managers.PluginManager: Loading plugin 'ALE Restart Watchdog' (v1.0.2.1)
20:26:05.0441 [INFO]   Torch.Managers.PluginManager: Loading plugin at ALE_ShipFixer.ShipFixerPlugin
20:26:05.0441 [INFO]   Torch.Managers.PluginManager: Loading plugin 'ALE ShipFixer' (v1.0.5.3)
20:26:05.2091 [INFO]   Torch.Managers.PluginManager: Loading plugin at Essentials.EssentialsPlugin
20:26:05.2091 [INFO]   Torch.Managers.PluginManager: Loading plugin 'Essentials' (v1.7.1.71-139-ge1d9406)
20:26:05.2601 [INFO]   Torch.Managers.PluginManager: Loading plugin at Profiler.ProfilerPlugin
20:26:05.2601 [INFO]   Torch.Managers.PluginManager: Loading plugin 'Profiler' (v3.1.0.8)
20:26:05.2801 [INFO]   SEPerformanceFix.SEPerformanceFix: MyWindTurbinePatch successfull!
20:26:05.2801 [INFO]   Torch.Managers.PluginManager: Loading plugin at SEPerformanceFix.SEPerformanceFix
20:26:05.2801 [INFO]   Torch.Managers.PluginManager: Loading plugin 'SE PerformanceFix' (v1.0.1)
20:26:05.3171 [INFO]   Essentials: Attempting to load config from C:\Servers\Torch SPE\Instance\Essentials.cfg
20:26:05.3651 [INFO]   Torch.Managers.PluginManager: Loaded 6 plugins.
20:26:05.3841 [WARN]   Torch.VRageGame: Steam service is not running! Please reinstall dedicated server.
20:26:05.7051 [INFO]   InstanceManager: Loading instance C:\Servers\Torch SPE\Instance
20:26:05.7661 [ERROR]  InstanceManager: Failed to load world at path: C:\Servers\Torch SPE\Instance\Saves\Gamerz mining Red Planet LOS
20:26:05.7661 [WARN]   InstanceManager: No worlds found in the current instance C:\Servers\Torch SPE\Instance.
20:26:05.7661 [INFO]   Torch: Initialized server 'Torch' at 'C:\Servers\Torch SPE\Instance'
20:26:05.7661 [INFO]   Torch: Starting server.
20:26:05.7841 [FATAL]  Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
   at Patched_Sandbox.MySandboxGame.ctor_0(Object windowHandle, String[] , IntPtr )
   at SpaceEngineers.Game.SpaceEngineersGame..ctor(String[] commandlineArgs)
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 237
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 125
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Patched_Sandbox.MySandboxGame.ctor_0(Object windowHandle, String[] , IntPtr )
   at SpaceEngineers.Game.SpaceEngineersGame..ctor(String[] commandlineArgs)
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 237
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 125
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
20:26:05.7841 [INFO]   Initializer: Generating minidump at C:\Servers\Torch SPE\Instance\Minidump.dmp
20:26:05.7841 [ERROR]  Initializer: Keen broke the minidump, sorry.
```

Installed a fresh Torch Server, broken too. Folder messed up with dedicated server files again
Directly after first start:

```
21:29:47.3132 [INFO]   PatchManager: Patching begins...
21:29:47.4132 [INFO]   PatchManager: Patched 2/12.  (16%)
21:29:47.4132 [INFO]   PatchManager: Patched 3/12.  (25%)
21:29:47.4132 [INFO]   PatchManager: Patched 4/12.  (33%)
21:29:47.4222 [INFO]   PatchManager: Patched 5/12.  (41%)
21:29:47.4222 [INFO]   PatchManager: Patched 6/12.  (50%)
21:29:47.4222 [INFO]   PatchManager: Patched 8/12.  (66%)
21:29:47.4222 [INFO]   PatchManager: Patched 9/12.  (75%)
21:29:47.4222 [INFO]   PatchManager: Patched 10/12.  (83%)
21:29:47.4222 [INFO]   PatchManager: Patched 11/12.  (91%)
21:29:47.4222 [INFO]   PatchManager: Patched 12/12.  (100%)
21:29:47.4222 [INFO]   PatchManager: Patching done
21:29:47.4592 [INFO]   PromotePatch: patching promote
21:29:47.4842 [INFO]   Torch: Initializing server
21:29:48.4012 [INFO]   Torch: RELEASE
21:29:48.4012 [INFO]   Torch: Torch Version: v1.3.1.130-master
21:29:48.4012 [INFO]   Torch: Game Version: 1.197.63
21:29:48.4012 [INFO]   Torch: Executing assembly: Torch.Server, Version=1.3.1.130, Culture=neutral, PublicKeyToken=null
21:29:48.4012 [INFO]   Torch: Executing directory: C:\Servers\Torch Final\
21:29:48.4082 [INFO]   PluginManager: Loading plugins...
21:29:48.4082 [INFO]   PluginManager: Checking for plugin updates...
21:29:48.4082 [INFO]   PluginManager: Updated 0 plugins.
21:29:48.4202 [INFO]   PluginManager: Loaded 0 plugins.
21:29:48.5332 [WARN]   VRageGame: Steam service is not running! Please reinstall dedicated server.
21:29:48.6202 [INFO]   InstanceManager: Loading instance C:\Servers\Torch Final\Instance
21:29:48.7012 [WARN]   InstanceManager: No worlds found in the current instance C:\Servers\Torch Final\Instance.
21:29:48.7012 [INFO]   Torch: Initialized server 'Torch' at 'C:\Servers\Torch Final\Instance'
21:29:49.4607 [WARN]   UpdateManager: Updating Torch from version v1.3.1.130-master to version v1.3.1.133-master
21:29:51.9322 [WARN]   UpdateManager: Torch version v1.3.1.133-master has been installed, please restart Torch to finish the process.
```

**Comment by DoktorKrove** [comment]
Looks like v1.3.1.133-master  fixed the issue

**Comment by sysworx** [comment]
Yeah looks like
