### ISSUE TITLE
Torch shuts itself down instead of normal server restart after XX minutes

### ISSUE THREAD

**Issue by Crash0v3r1de** [TorchAPI/Torch#416]
- [X] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [X] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
    -I can provide remote access into my server if needed
- [ ] Is this a suggestion?

**Torch Version:** v1.3.1.136-master **SE Version:** 1.197.65

### Expected Behavior
What did you expect to happen?
Auto restart via DedicatedServer.cfg causes Torch to just completely shutdown, non functional server restart ONLY when using Torch. Works totally fine with the Vanilla DedicatedServer.

### Observed Behavior
What actually happened?
-Torch killed itself and never came back up. Stopped SE server and completely closed the Torch client.

### Steps to Reproduce
1. How did this issue get triggered?
  -Fresh torch install with fresh vanilla world migration to the Torch Instance with a few plugins added to Torch.
2. Write the steps here.
  - Install torch, copy Instance files, add plugins, restart Torch, Start server, wait for auto restart - notice it closes itself and never comes back up.

### Other Information
Provide links to game logs or saves here if necessary.
This is the only thing in the logs before Torch shut itself down.

02:37:26.6840 [INFO]   Chat: [Global:0] Good.bot: WARNING! Server will restart in 10 minutes
02:42:26.7162 [INFO]   Chat: [Global:0] Good.bot: WARNING! Server will restart in 5 minutes
02:46:26.7790 [INFO]   Chat: [Global:0] Good.bot: WARNING! Server will restart in 1 minute
02:47:26.8259 [INFO]   Torch.Session.TorchSessionManager: Unloading torch session for <Server name>
02:47:27.0603 [INFO]   CrunchUtilities.CrunchUtilitiesPlugin: Session-State is now Unloading
02:47:27.0759 [INFO]   Torch.Server.Managers.MultiplayerManagerDedicated: Removed steam authentication intercept

**Comment by Crash0v3r1de** [comment]
lol this time it didn't shutdown torch it just never brought the SE server back up and Torch says the server is still running.

`15:34:11.6773 [INFO]   Keen:    Saving Sandbox world configuration file C:\ProgramData\SpaceEngineersDedicated\SE Main Service\Saves\Earth Planet\.new\Sandbox_config.sbc
15:34:13.2399 [INFO]   Keen: MyLights Unloading data.
15:34:13.5368 [INFO]   Keen: Logging off Steam...
15:34:13.5368 [INFO]   Keen: Shutting down server...
15:34:13.6774 [INFO]   Keen: Done
15:34:14.3336 [INFO]   TorchSessionManager: Unloaded torch session for <server name>
15:34:14.3336 [INFO]   SEDiscordBridgePlugin: Unloading Discord Bridge!
15:34:14.3336 [INFO]   SEDiscordBridgePlugin: Discord Bridge Unloaded!
15:34:14.3336 [INFO]   Keen: TORCH MOD: Unregistering mod communication.`

**Comment by Jimmacle** [comment]
Should be fixed by now via a Keen game update
