### ISSUE TITLE
Problem of Instance creation

### ISSUE THREAD

**Issue by ghost** [TorchAPI/Torch#419]
**Torch Version:** 1.3.1.136 **SE Version:** 1.197

I would like to report a problem on your new version of torch it would appear that it is impossible to create a New World from your application.

By choosing any card it gives me an error message.

### Other Information
I would like to make it clear that when using Torch to create a new Instance

**Comment by RhythmNz** [comment]
me too

**Comment by dorimanx** [comment]
Yes, problem is there.
only way now is to open DedicatedServer64 server, create world, with all settings, then copy it from
c:\Users\USER-HERE\AppData\Roaming\SpaceEngineersDedicated\Saves\
to instance/saves

**Comment by Jimmacle** [comment]
Should be fixed now; Keen changed the format of the premade world directories.
