### ISSUE TITLE
GUI hung via spam log msg

### ISSUE THREAD

**Issue by foogs** [TorchAPI/Torch#421]
- [+] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [+] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [-] Is this a suggestion?

### Expected Behavior
Shit load of log msg easy eaten by torch

### Observed Behavior
GUI hung

### Steps to Reproduce
1. Trigger some log / or via plugin loop with msg

**Comment by N1Ran** [comment]
Log was not provided.  Closing issue
