### ISSUE TITLE
[1.3.1.138] Fatal error during dedicated server init see log for more information.

### ISSUE THREAD

**Issue by shortybsd** [TorchAPI/Torch#423]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.138 **SE Version:** 1.197.073

### Expected Behavior
What did you expect to happen?
For the server to auto-restart as normal.

### Observed Behavior
What actually happened?
Torch had fatal error upon next auto-restart.

### Steps to Reproduce
1. Launch Torch
2. Start server.
3. Go to Entity Manager, delete any unnamed grid e.g. Large Grid 2121.
4. Wait for next auto-restart.

### Other Information
[Combined Torch Log + Keen Log](https://pastebin.com/gMjFz8zB)

Extra Notes: I run Essential plugin & SEDiscordBridge plugin. Also this is a modded server, yet will crash with same exact error with no mods on server.

This is a a bit contradicting.
````
18:09:04.3610 [DEBUG]  Keen:    Bind IP : 10.0.0.100:27010
18:09:20.0316 [INFO]   Keen:    Error: No IP assigned.
````

**Comment by N1Ran** [comment]
keep ip set to 0.0.0.0.
