### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by woeisme** [TorchAPI/Torch#429]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [* ] Is this a suggestion?

**Torch Version:** 1.x.xxx.xxx **SE Version:** 1.xxx.xxx

### Expected Behavior
Install Space engineers dedicated torch server on linux

### Observed Behavior
No method to do so

### Steps to Reproduce
1. went to torch website / wiki and github
2. Searched for linux instructions

### Other Information
It seems to be possible to run on linux via docker container using wine (https://github.com/mmmaxwwwell/space-engineers-dedicated-docker-linux) 
Would be nice to have a version of Torch that did similiar.

**Comment by N1Ran** [comment]
Torch does not officially support Linux.
