### ISSUE TITLE
Steam collections get added to mods list, creating in-game errors

### ISSUE THREAD

**Issue by rcdailey** [TorchAPI/Torch#437]
When I add a collection ID to the mods list, Torch properly installs all the mods in that collection. However, it also adds the collection itself to the mods list. From `Sandbox_config.sbc`:

```xml
    <ModItem FriendlyName="Jailbroken's SE Mods">
      <Name>2412302307.sbm</Name>
      <PublishedFileId>2412302307</PublishedFileId>
      <PublishedServiceName>Steam</PublishedServiceName>
    </ModItem>
    <ModItem FriendlyName="Space Engineer's Collection No.1">
      <Name>2398016133.sbm</Name>
      <PublishedFileId>2398016133</PublishedFileId>
      <PublishedServiceName>Steam</PublishedServiceName>
    </ModItem>
```

These two are collections from [here](https://steamcommunity.com/sharedfiles/filedetails/?id=2412302307) and [here](https://steamcommunity.com/sharedfiles/filedetails/?id=2398016133).

When I load into the game, I get this error:

![image](https://user-images.githubusercontent.com/1768054/109691114-b8050600-7b4c-11eb-96d5-48f0cf2c118f.png)

My gut feeling here is that Torch should utilize the collection to download mods inside it, but not add it to the mods list so that Keen loads it as a mod itself (because it isn't). This error when players join my server is quite annoying.

Torch version: `1.3.1.144`

**Comment by Bishbash777** [comment]
Most likely resolved by keen mod changes - re-open if it is not the case

**Comment by rcdailey** [comment]
Not to sound haughty and rude, but I personally feel you should have verified this prior to closing the issue.
