### ISSUE TITLE
Cannot delete grids of players not on server

### ISSUE THREAD

**Issue by Raveyist** [TorchAPI/Torch#44]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

Torch 1.0.182.329, SE 1.181.502

### Expected Behavior
What did you expect to happen?
I wanted to delete all grids relating to player DukkyJr

### Observed Behavior
Initially nothing happed except for an error that "DukkyJr does not exist"
I assumed that Torch was trying locate all grids for DukkyJr but any grids owned by players not only show up as DukkyJr [dead] on the control panel

I then tried using /delete grids ownedby DukkyJr [dead] - Then the server crashed

### Steps to Reproduce
As above

1. How did this issue get triggered?

Entering the following command triggers the crash: /delete grids ownedby DukkyJr [dead]

2. Write the steps here.

### Other Information
https://pastebin.com/NX8tCVgb
My server: 95.154.229.151:28015

**Comment by Varaxian** [comment]
Good bug report!

If I recall correctly, this is due to concealment. Jim is working on pushing the fix out, but as a get-by process, disable concealment, then /reveal all, then run your cleanup.

**Comment by Jimmacle** [comment]
Torch can only resolve player names when they're online because of Reasons, use their identity ID instead of their name.
