### ISSUE TITLE
Running Torch not interactively in Windows 10 causes immediate shutdown upon program start

### ISSUE THREAD

**Issue by ares6au** [TorchAPI/Torch#449]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [x] Is this a suggestion?

**Torch Version:** v1.3.1.149 **SE Version:** Doesn't matter, we don't get that far.

### Expected Behavior
What did you expect to happen?
When starting Torch in non-interactive mode on Windows 10, expect Torch.exe not to turn itself off almost immediately.

### Observed Behavior
What actually happened?
Torch.exe turns off almost immediately after starting.

### Steps to Reproduce
1. How did this issue get triggered?
Run Torch under something that will make it non-interactive (Such as with a GSP panel, UGCC would be a good starting point as this is where we're seeing the issue. Batch files work too.
2. Write the steps here.
Start Torch under something that runs it non-interactively
Watch Task Manager, see Torch blip on and off
For reference, open Torch normally via the Windows GUI. See that it works as per normal.

### Other Information
Provide links to game logs or saves here if necessary.

There is already a catch block for Windows Server 2019 - would be nice if this catch block was extended to Windows 10 as well, or non-OS-specific even. Line 63 it starts for reference in https://github.com/TorchAPI/Torch/blob/master/Torch.Server/Program.cs

**Comment by zznty** [comment]
i have reproduced this issue with UGCC.
I will try to workaround the issue.
