### ISSUE TITLE
System.NullReferenceException triggered after clicking  [Add Role] button

### ISSUE THREAD

**Issue by raulortizquiroga** [TorchAPI/Torch#451]
**Torch Version:** 1.3.1.149-master**

### Expected Behavior
What did you expect to happen?

### Observed Behavior
What actually happened?
The message "Torch encountered a fatal error and needs to close. Please check the logs for details." is displayed. The last row of the los is [ERROR]  Initializer: Keen broke the minidump, sorry.

### Steps to Reproduce
1. How did this issue get triggered?
After clicking the Add Role button
2. Write the steps here.
Once Torch is opened click in the Add Role button

### Other Information
[Torch-2021-07-20_.log](https://github.com/TorchAPI/Torch/files/6852325/Torch-2021-07-20_.log)
[Keen-2021-07-20.log](https://github.com/TorchAPI/Torch/files/6852330/Keen-2021-07-20.log)

**Comment by Bishbash777** [comment]
Fixed long time ago
