### ISSUE TITLE
(Website related issue) Torch download page throwing error.

### ISSUE THREAD

**Issue by ZephyrFerret** [TorchAPI/Torch#456]
**Torch Version:** 1.x.xxx.xxx **SE Version:** 1.xxx.xxx 
(This is a website related issue)

### Expected Behavior
Visit the website and be able to download the Dedicated server. https://torchapi.net/download

### Observed Behavior
Error page displays.

### Steps to Reproduce
Simply visit the download page on the website.

### Other Information
I couldn't find a website related wiki for torch so i decided here would be the best place? anyway.
Below I have a screenshot of the message that's displayed when visiting the page. it can't be a "me" issue as I have tried this on multiple devices, even my phone on mobile data (To test if it was something with my network)

![image](https://user-images.githubusercontent.com/78930149/135701171-42dcdb1b-383d-4185-97be-86abeddd4212.png)

**Comment by Jimmacle** [comment]
Known server-side issue, however the error doesn't make any sense so I'm taking the opportunity to fix a lot of the other issues with the website and just relaunch the whole thing. You can get Torch from this link in the meantime: https://build.torchapi.net/job/Torch/job/Torch/job/master/lastSuccessfulBuild/artifact/bin/torch-server.zip

**Comment by Bishbash777** [comment]
Closed as not relevant anymore
