### ISSUE TITLE
Urgent! Ask for help!! My server cannot start!

### ISSUE THREAD

**Issue by 2631692637** [TorchAPI/Torch#460]
**Torch Version:** 1.31.169**SE Version I don't know

### Expected Behavior
What did you expect to happen?
The server cannot start

### Observed Behavior
What actually happened?
The server cannot start

### Steps to Reproduce
1. How did this issue get triggered?
2. Write the steps here.
[Desktop.zip](https://github.com/TorchAPI/Torch/files/7899951/Desktop.zip)

Click "start" to report an error after jamming

### Other Information
Provide links to game logs or saves here if necessary.
[Desktop.zip](https://github.com/TorchAPI/Torch/files/7899955/Desktop.zip)

**Comment by 2631692637** [comment]
Thank you for your great help. This is my first time to use the torch. All three environments have been installed normally

**Comment by 2631692637** [comment]
[Logs.zip](https://github.com/TorchAPI/Torch/files/7899969/Logs.zip)

**Comment by Bishbash777** [comment]
Please seek assistance in our discord
