### ISSUE TITLE
Torch Website not working???

### ISSUE THREAD

**Issue by Igorzcech** [TorchAPI/Torch#464]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [x] Is this a suggestion?

**Torch Version:** 1.x.xxx.xxx **SE Version:** 1.xxx.xxx

### Expected Behavior
Torch Website not working

### Observed Behavior
Website not work

### Steps to Reproduce
1. How did this issue get triggered?
2. Write the steps here.

### Other Information
Provide links to game logs or saves here if necessary.

**Comment by arunasp** [comment]
Hello,

It looks like the documentation need update after torchapi being handed over. The torcapi.net website is dead now and the readme file is sending to dead links.
Could be nice if documentaion on github could just link github instead torchapi.net and devs would use github for torchapi binary packages too.

For now change links when copying torchapi.net => torchapi.com
