### ISSUE TITLE
[BUG] When updating player block limits on an existing world, those updates do not save.

### ISSUE THREAD

**Issue by Varaxian** [TorchAPI/Torch#47]
**Torch Version:** 1.0.182.329 **SE Version:** 1.182.018

### Expected Behavior
Saved Block limits

### Observed Behavior
Nope

### Steps to Reproduce
1.) Set new Block Limits
2.) Hit all of the saves
3.) Try every method of starting and shutting down TORCH to save config.
4.) No modification made

**Comment by Jimmacle** [comment]
Fixed 82815f66e5384b8e8427d50720e23aebd3e10da0
