### ISSUE TITLE
how can i start/stop torch from command line without interacting with gui

### ISSUE THREAD

**Issue by zarozak** [TorchAPI/Torch#48]
this is to allow me to stop torch/se to apply an update
I can auto detect and update and install it, but cannot currently cleanly shut the server down to apply it

is there a way to do this?

**Comment by Jimmacle** [comment]
You can use the ingame chat commands.

**Comment by zarozak** [comment]
Sorry but I don't understand how I can do this, would you mind explaining a bit more. I wish to run a windows cmd script to shutdown torch and allow an update to be applied and I don't see anything that mentions shutdown in forums or any user comments. Appreciate your assistance if possible

Regards

Paul Sexstone
