### ISSUE TITLE
crash when joining server after switching to torch api

### ISSUE THREAD

**Issue by mindforger** [TorchAPI/Torch#507]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.198 **SE Version:** 1.201.13

### Expected Behavior
People able to join server without getting crashed

### Observed Behavior
Gradually more and more people having issues connecting, getting supposedly "driver crash" but able to connect to other servers just fine

issue seems to be amplified when sitting in a cryo chamber or floating, launching from respawn screen seems fine but is uselss due to loosing your inventory everytime. 

### Steps to Reproduce
get crashed at join right before loading UI and seeing space after a few hours working fine after switch to torch server.
Then gradually getting crashed more often within hours until not able to join anymore without being killed ... at this time of point i can not join at all

### Other Information
reset everything, DDU audio and GPU reset, reinstalled game, unsubbed all contents, deleted all SE related files from roaming etc. ...

the only thing we changed was to switch to torch as is loads mods better than vanilla

**Comment by Bishbash777** [comment]
No logs = No support. Please send logs or crash errors
