### ISSUE TITLE
Crash: checking or unchecking 'conceal pirates' instantly crashes torch with angry stuff.

### ISSUE THREAD

**Issue by XeroCreator** [TorchAPI/Torch#53]
### Expected Behavior
What did you expect to happen?
button to be clicked.

### Observed Behavior
button clicked, angry red text ensues, server restart in 5 second message appears.(that might be me and auto-restart)

### Steps to Reproduce
1. start server with torch and essentials/concealment (i have both)
2. click conceal pirates on or off
3. look at angry text and fix it.

**Comment by Jimmacle** [comment]
Please upload angry text to Pastebin and add it to your report.

**Comment by XeroCreator** [comment]
angry text was under 'other information' but guess it never posted the update. fml. 
if you just click conceal pirates it does it tho.

**Comment by kurazarrh** [comment]
I am not experiencing this issue, as of Torch 1.1.229.265, SE 1.183.16, with Concealment 1.2.1 enabled. Torch does not crash, and it appears to correctly conceal and reveal both pirate and non-pirate grids.

Further in-game testing may be necessary, but at the moment all I have access to is the server console.

**Comment by Jimmacle** [comment]
Assuming this is fixed due to the lack of complaints.
