### ISSUE TITLE
Arguments to torch startup

### ISSUE THREAD

**Issue by zarozak** [TorchAPI/Torch#54]
Hi, I'm unable to get command line arguments "nogui" and "autostart" to work
I added to command eg : torch.server nogui autostart 
this failed to start or prevent gui, is this the correct usage of these items, and if not please let me know where they should be placed.

**Comment by Varaxian** [comment]
-autostart -restartoncrash

**Comment by zarozak** [comment]
thanks, I was missing the "-"
