### ISSUE TITLE
05:54:38.6114 FATAL ERROR 

### ISSUE THREAD

**Issue by GDannyboy** [TorchAPI/Torch#541]
- [X] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [X] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [X] Is this a suggestion? No

Torch Version:1.1.207.7

### Expected Behavior
What did you expect to happen? That Torch Server client for Space Engineers would run completely.

### Observed Behavior
What actually happened? It failed.

### Steps to Reproduce
1. How did this issue get triggered? Running the program after the installation was completed.
2. Write the steps here. Ran the .exe command file.

### Other Information
Provide links to game logs or saves here if necessary.

Screenshot of error message: https://1drv.ms/i/s!ApxoK14J0TEe8-E2hi3mymE7TVvkuw?e=QaGH2i

**Comment by Bishbash777** [comment]
Torch Version:1.1.207.7 is super old, make sure you are you are using the latest version available at https://torchapi.com
