### ISSUE TITLE
Not Torchapi.com connection

### ISSUE THREAD

**Issue by three7s** [TorchAPI/Torch#546]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)

**Torch Version:** 1.3.1.228 **SE Version:** 1.202.68

### Expected Behavior
What did you expect to happen?
Clean loadup

### Observed Behavior
What actually happened?
11:25:46.1943 [ERROR]  PluginQuery: Plugin query returned response 522
11:25:46.1943 [WARN]   PluginManager: Plugin Profiler does not have any releases on torchapi.com. Cannot update.
11:25:46.2605 [ERROR]  PluginQuery: Plugin query returned response 522
11:25:46.2605 [WARN]   PluginManager: Plugin Concealment does not have any releases on torchapi.com. Cannot update.

### Steps to Reproduce
1. Start server with plugins (essentials), happens when checking for plugin updates checks

**Comment by Bishbash777** [comment]
resolved
