### ISSUE TITLE
[Bug report]Torch will set the procedural density back to 0.25 automatically

### ISSUE THREAD

**Issue by haximodor92** [TorchAPI/Torch#55]
- [ yes] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ yes] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ no] Is this a suggestion?

**Torch Version:** 1.0.182.329 **SE Version:** 1.182.102

### Expected Behavior
What did you expect to happen?
After I modify the sandbox.sbc file, the game should be the procedural density I modify.

### Observed Behavior
What actually happened?
Torch will automatically modify the sandbox.sbc file and set the procedural density back to 0.25 and procedural seed to 0. 
### Steps to Reproduce
1. How did this issue get triggered?
2. Write the steps here.
1)modify the sanbox.sbc, change the number of procedural density and seed to any number. 
2)Click torch to open a server with the corresponding saves.
3)Open again the sanbox.sbc, you'll find the procedural density has been switched back. 

### Other Information
Provide links to game logs or saves here if necessary.

**Comment by Varaxian** [comment]
Interesting. I will verify reproduction for this. If it's happened, I've missed it myself

**Comment by kurazarrh** [comment]
What's happening here is that if you want to modify the procedural density or seed for an existing world, you need to change it both in the .sbc file, as well as in the SpaceEngineers-Dedicated.cfg file. If you don't change it in the .cfg file, then Torch will read the file and overwrite the .sbc file's settings when it saves.

Try changing it in both places and let us know if it is resolved.

**Comment by Varaxian** [comment]
And before you have a torch instance loaded. You can also use the vanilla
configurator to do this in a GUI and save the files

**Comment by Jimmacle** [comment]
This should be fixed in 82815f66e5384b8e8427d50720e23aebd3e10da0, there was a bug with saving config changes.
