### ISSUE TITLE
incorrect spelling of plugins

### ISSUE THREAD

**Issue by Arbel-arad** [TorchAPI/Torch#556]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [X] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.234 **SE Version:** 1.202.117

### Expected Behavior
"local plugins" description spelling of "plugins"

### Observed Behavior
"pluhins" instead of "plugins"

### Steps to Reproduce
hover the mouse over the local plugins option on the configuration >> torch section.

### Other Information
![image](https://github.com/TorchAPI/Torch/assets/65590498/6084d9fc-7b06-493e-b938-d52afcb1f7cf)

**Comment by Bishbash777** [comment]
Game breaking bug finally fixed. Rejoice!
