### ISSUE TITLE
Shutdown torch server from os command line (to allow scripted shutdown)

### ISSUE THREAD

**Issue by zarozak** [TorchAPI/Torch#57]
is it possible to send a "say /quit" to the server from the OS command line where torch is running? or some other way to shutdown server neatly.

I have setup a script to check for updates but want to trigger torch to shutdown to then detect and apply them when found. 

Torch detects them on startup and applies, but I am trying to have them apply when they are released so have another script checking on a regular basis.

**Comment by Jimmacle** [comment]
Torch doesn't currently support any service-like interaction from outside the application itself. I'll consider adding this when I start working on service support in general.

**Comment by GornyakManiac** [comment]
Yeah, I have the same situation with external restart script, which edits save file on server restart.
