### ISSUE TITLE
Use of IMyCharacter.Kill() in mod scripting will kill and then soft-lock the player

### ISSUE THREAD

**Issue by FlatulentMoth** [TorchAPI/Torch#575]
- [DONE] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [Resources Provided Below] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [NO] Is this a suggestion?

**Torch Version:** Current as of Feb/10/2024 **SE Version:** 1.203.6

### Expected Behavior
The player was to be killed (via IMyCharacter.Kill() ) and be brought to the respawn menu

### Observed Behavior
The player was killed, but the respawn menu never opened.

### Steps to Reproduce
1. use a mod that employs IMyCharacter.Kill()
2. run the code that triggers the method

### Other Information
found issue when using this game mod https://steamcommunity.com/sharedfiles/filedetails/?id=3154386199

server logs below:

[Torch-2024-02-10.log](https://github.com/TorchAPI/Torch/files/14231314/Torch-2024-02-10.log)
[Keen-2024-02-10.log](https://github.com/TorchAPI/Torch/files/14231316/Keen-2024-02-10.log)

should generate same results on otherwise vanilla setup

**Comment by zznty** [comment]
Does the issue persist only on the Torch server or on vanilla too? If it's not related to Torch itself, you may want to ask Keen support instead.

**Comment by FlatulentMoth** [comment]
the issue only persists on the Torch Server.

the expected behavior was achieved when using a multiplayer vanilla game

**Comment by zznty** [comment]
> the expected behavior was achieved when using a multiplayer vanilla game

When hosting multiplayer lobby from client or using keen dedicated server? they're not the same thing.

**Comment by FlatulentMoth** [comment]
It was hosted through the game client. I assume though that Keen Dedicated _should_ have the same behavior as the client

**Comment by FlatulentMoth** [comment]
Update: this is not an issue with torch, but also with Keen Dedicated as well
