### ISSUE TITLE
[BUG] Concealment causing a No Save scenario

### ISSUE THREAD

**Issue by Varaxian** [TorchAPI/Torch#58]
From multiple investigations from multiple people, TORCH eventually stops saving due to a specific GUID issue. Someone has found that the GUID responsible is Concealment.

I'll skip the rest of the format for now.

**Comment by Jimmacle** [comment]
The warning about the GUID will not stop a world from saving.

**Comment by Varaxian** [comment]
https://pastebin.com/h7yiG4cv
