### ISSUE TITLE
[BUG] + [FR] - Torch does not taskkill TORCH process on crash causing a "No Save" scenario on start of new process.

### ISSUE THREAD

**Issue by Varaxian** [TorchAPI/Torch#60]
**Torch Version:** 1.1.207.7 **SE Version:** 1.182.103

Summary:
In the event that TORCH crashes, RestartOnCrash enabled, Torch will start a new instance on-top of the currently crashed instance, therefor giving it no access to worldfiles and causing a "No Save" scenario.

### Expected Behavior
- On crash or timeout, a taskkill event on Torch instance.

### Observed Behavior
- Bugged torch instance continues to run.
- New instance cannot write to world files because they are being utilized by crashed instance

### Steps to Reproduce 
(Not 100% repro, as the process does NOT always stick around on crash)
1. Crash torch
2. Note if Torch process remains running (regardless of GUI or Command Prompt being open)
3.) If so, launch new Torch
4.) Attempt to save
5.) Check world file modification timestamp

### Feature request
- Include a taskkill of TORCH process on non-responsive or crashed instance/behavior before a new instance of TORCH is launched.

**Comment by Jimmacle** [comment]
Fixed 2f3b6cdda7444d84604d209b1f5f02454e0d0ab3, the new Torch process should kill the old one if it doesn't exit in time.
