### ISSUE TITLE
[BUG] TORCH GUI allows you to switch WORLD location while world is loaded, causing crash

### ISSUE THREAD

**Issue by Varaxian** [TorchAPI/Torch#61]
**Torch Version:** 1.1.207.7 **SE Version:** 1.182.103

### Expected Behavior
Once world starts, all folder locations to be locked and not modifiable.

### Observed Behavior
Torch world location can be accidentally or intentionally switched while the world is loaded, causing crash.

### Steps to Reproduce
1. Launch TORCH
2. After world loads, change the world location in the "World:" dropdown
3. Crash

**Comment by Jimmacle** [comment]
Fixed 97da740e7edf8ab4fa8fbe41843cf2c037de6849, disabled entire config panel when the server is running.
