### ISSUE TITLE
MissingMethodException on Windows Server 2008 R2 - Int32 System.Environment.get_CurrentManagedThreadId()

### ISSUE THREAD

**Issue by Jonathan-Rosewood** [TorchAPI/Torch#66]
**Torch Version:** 1.1.213.390 **SE Version:** unknown

### Observed Behavior
[screenshot](http://prntscr.com/g4hh91)

### Other Information
I'm running Windows Server 2008 R2 with NET Framework 4.0.30319

**Comment by Varaxian** [comment]
Need to run framework 4.61 and above

**Comment by Jonathan-Rosewood** [comment]
The problem solved with the installation of NET Framework version 4.5.
But since nothing is specified in the requirements, and the application asks for the first launch of NET Framework 4.0, and @Varaxian speaks about NET Framework 4.6.1...
I do not even know what could be worse!

**Comment by Varaxian** [comment]
Space Engineers itself is based on 4.61.

Totally understand that it isn't common knowledge, but those are the facts. 4.61+ if you want to not have issues

**Comment by TheAmazingTaco** [comment]
I'm having the same issue (not sure how to log), and i have 4.61+ installed
