### ISSUE TITLE
[FATAL] Torch: System.MissingMethodException - win10

### ISSUE THREAD

**Issue by vladus06** [TorchAPI/Torch#78]
Help me please

Torch 1.1.229.265, SE 1.182.304
Running Windows 10 with NET Framework 4.6.01586 
![Screenshot](https://image.ibb.co/exr96k/torch.jpg)

(Old SEServerExtender is worked.)

**Comment by Jimmacle** [comment]
It looks like you're using an outdated version of Torch. Join the Discord server and check #general's pinned messages, we're currently in the middle of moving to a new automatic release system so Torch releases are kind of all over the place right now.
