### ISSUE TITLE
Chat scroll, uptime, import prefabs, entity search and sort, send text to select player

### ISSUE THREAD

**Issue by szczepix** [TorchAPI/Torch#83]
Suggestions:
- [x] Add autoscroll checkbox field in Server Chat tab -> [d20d68b](https://github.com/TorchAPI/Torch/commit/d20d68b831eb9e9b234f3fa3830e52c3eb099250)
- [ ] Add new command: `!uptime` it return server uptime
- [ ] Feature like add ship into server something like import in SESE
- [ ] Search input on Entity List
- [ ] Sort grids with owner name
- [ ] Command or Button with send Message to selected Player

**Comment by Gladi** [comment]
Id like to add

- [ ] Promote/Demote via Server Chat tab

**Comment by Equinox-** [comment]
Automatically scrolls when you're already scrolled to the bottom.  If you aren't scrolled to the bottom it leaves it alone.
d20d68b831eb9e9b234f3fa3830e52c3eb099250
