### ISSUE TITLE
World file is corrupted

### ISSUE THREAD

**Issue by fr33soul** [TorchAPI/Torch#86]
Torch 1.1.229.265 - Compatibility and Bugfixes

### Expected Behavior
that game runs at least..

### Observed Behavior
when a try to enter via client it shows me this error msg: world file is corrupted and can't be loaded

### Steps to Reproduce
1. How did this issue get triggered?
 dont know
2. Write the steps here.
i followed this video https://www.youtube.com/watch?v=M5_6iPOTFWI&t=260s

### Other Information
Provide links to game logs or saves here if necessary.

**Comment by kamikaze0310** [comment]
Download the RC1 version of Torch (not in GITHUB). Its located in pinned messages in the general channel in torch discord.

**Comment by fr33soul** [comment]
theres nothing pinned in general chat..

**Comment by kamikaze0310** [comment]
Its there I promise...i'm looking at it now

**Comment by kamikaze0310** [comment]
https://cdn.discordapp.com/attachments/230191591640268800/348631347327401998/Torch.Server.1.1.231.536-RC1.zip

**Comment by Jimmacle** [comment]
Kamikaze is correct, this issue is already fixed.
