### ISSUE TITLE
!Ban/!Unban commands doesn't work

### ISSUE THREAD

**Issue by GornyakManiac** [TorchAPI/Torch#89]
**Torch Version:** 1.1.229.265 **SE Version:** 1.183.102

### Expected Behavior
!ban or !unban commands should ban/unban players regardless of whether the player is currently on the server or not

### Observed Behavior
!ban command bans player only if player are playing on server at the moment. !unban command doesn't work at all. Both commands return "Player not found." in this cases.

### Steps to Reproduce
1. Try to ban or unban any player which currently not playing on server via !ban/!unban commands.

**Comment by Equinox-** [comment]
TorchAPI/Essentials#21
