### ISSUE TITLE
Definition Browser

### ISSUE THREAD

**Issue by TheAmazingTaco** [TorchAPI/Torch#91]
I would like to see a block browser that easily lets us limit the blocks on a server for both individuals and factions.    It would be awesome if this was manageable from in game so modded blocks could be added to a limit list fairly easily. 

Jimmacle is a god who opposed the almighty Clang. Let his light envelope and protect you from all Clang in your future.

**Comment by szczepix** [comment]
Maybe you can add definition import? #83
