### ISSUE TITLE
chat does not scroll properly/longhelp causes scroll bug

### ISSUE THREAD

**Issue by XeroCreator** [TorchAPI/Torch#96]
- [yes] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [yes] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [no] Is this a suggestion?

**Torch Version:** 1.1.229.265 **SE Version:** 1.183.200

### Expected Behavior
What did you expect to happen? chat to scroll properly?

### Observed Behavior
What actually happened? Chat did not scroll properly

### Steps to Reproduce
1. Basically, just start a server, doesn't matter what world etc. 
if you use the !longhelp command in server chat the actual chat/players message box does not scroll properly to the command at all, it sort of sticks on the chat screen regardless of what you scroll to, so you can't see the messages anyway. 
2. Just type !longhelp in chat/players in torch, and you'll see that the chat will not scroll correctly. (you also can't copy/paste because each message is locked or ... something? i don't know how to explain that.)
3. Anyway, you see that longhelp made chat extend but did not scroll down. if you send a couple messages to make the chat refresh it causes the chat to jump back up to the start of the longhelp message. 

side note: this may be caused by the way messages are structured and could be fixed if/when you get around to fixing the chat itself. 

### Other Information
also side note, auto-scroll down when new messages are shown would also be nice in general.

**Comment by Jimmacle** [comment]
Note for whoever fixes this: a good solution would be to change the chat view to a single TextBlock and add colored names that match the ingame chat while you're at it.

**Comment by Equinox-** [comment]
d20d68b831eb9e9b234f3fa3830e52c3eb099250

**Comment by Equinox-** [comment]
Fixed in [staging](https://build.torchapi.net/job/Torch/job/Torch/job/staging/lastSuccessfulBuild/)
