### ISSUE TITLE
Sporadic error loading game serializers

### ISSUE THREAD

**Issue by Sevka007** [TorchAPI/Torch#99]
Critical error happens after updating, it tells MISSING METHOD EXEPTIONS, method not found.
![image](https://user-images.githubusercontent.com/31598159/30006246-e02e085e-90fc-11e7-95f1-ad7166484afb.png)
sorry by Russian interface? but I think all you need is on English, please, help!

**Comment by Jimmacle** [comment]
Download the latest Torch "Staging" version from Jenkins. We're working out some kinks in the auto-deploy pipeline so the versions are a little messed up right now.

**Comment by Sevka007** [comment]
Now I have a different error
![image](https://user-images.githubusercontent.com/31598159/30012938-0380cedc-914c-11e7-8a77-9a15706616b4.png)

**Comment by ProsperCraft** [comment]
I may be having the same issue.

https://gist.github.com/ProsperCraft/22b3d992471cc6bc8fd2924d879d3adb

Same as my earlier bug report, hard coded directory links pointing to the jenkins folder that doesn't exist.

**Comment by Jimmacle** [comment]
Again, that is debug information and is entirely unrelated to the application trying to access files/directories. Read it closely.

**Comment by ProsperCraft** [comment]
I don't understand it, I can read Minecraft crash reports like the back of my hand, but I don't understand why this server is crashing on first load.

**Comment by Jimmacle** [comment]
I'm aware of that particular issue, it's nothing you can fix. You can avoid it for now by running the server with the `-nogui` argument which does what it sounds like.

**Comment by ProsperCraft** [comment]
Where do server arguments go in Torch?
